README.md, WORKSPACE, frontend/demo/BUILD, frontend/demo/nginx.conf, infrastructure/deployments/frontend-demo.yaml, infrastructure/network/istio-services.yaml, infrastructure/scripts/airy-conf.sh, infrastructure/scripts/status.sh, infrastructure/scripts/triggers/start.sh, infrastructure/scripts/triggers/stop.sh
=> Add alpine nginx image for demo app

backend/api/communication/BUILD, backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java, backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java, backend/api/communication/src/main/java/co/airy/core/api/communication/MessagesController.java, backend/api/communication/src/main/java/co/airy/core/api/communication/SendMessageController.java, backend/api/communication/src/main/java/co/airy/core/api/communication/WebSocketController.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ConversationResponsePayload.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/MessageResponsePayload.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/MessageUpsertPayload.java, backend/api/communication/src/test/java/co/airy/core/api/communication/WebSocketControllerTest.java, backend/api/communication/src/test/java/co/airy/core/api/communication/util/ConversationGenerator.java, backend/lib/mapping/BUILD, backend/lib/mapping/src/main/java/co/airy/mapping/ContentMapper.java, backend/lib/mapping/src/main/java/co/airy/mapping/model/Content.java, backend/lib/mapping/src/main/java/co/airy/mapping/model/Text.java, backend/lib/mapping/src/test/java/co/airy/mapping/ContentMapperTest.java, backend/lib/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/AuthConfig.java, docs/docs/api/http.md, docs/docs/api/websocket.md
=> Map outbound content model in communication app

backend/api/admin/src/main/java/co/airy/core/api/admin/ChannelsController.java, backend/api/admin/src/main/java/co/airy/core/api/admin/TagsController.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/CreateTagRequestPayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/DeleteTagRequestPayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/UpdateTagRequestPayload.java, backend/api/auth/src/main/java/co/airy/core/api/auth/controllers/UsersController.java, backend/api/auth/src/main/java/co/airy/core/api/auth/controllers/payload/InviteUserRequestPayload.java, backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java, backend/api/communication/src/main/java/co/airy/core/api/communication/SendMessageController.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ConversationByIdRequestPayload.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ConversationTagRequestPayload.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/MessageListRequestPayload.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/SendMessageRequestPayload.java, backend/api/communication/src/test/java/co/airy/core/api/communication/SendMessageControllerTest.java, backend/lib/payload/src/main/java/co/airy/payload/response/RequestErrorResponsePayload.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/ChatController.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/AuthenticationRequestPayload.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/SendMessageRequestPayload.java
=> Fix request NPEs

backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/ChatController.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Principal.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Stores.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/WebSocketController.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/Jwt.java, backend/sources/chat-plugin/src/test/java/co/airy/core/chat_plugin/ChatControllerTest.java, docs/docs/sources/chat-plugin.md
=> Fix chat plugin messaging behavior

backend/api/communication/src/main/java/co/airy/core/api/communication/WebSocketConfig.java, backend/api/communication/src/test/java/co/airy/core/api/communication/WebSocketControllerTest.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/WebSocketConfig.java
=> Add authentication to communication websocket

infrastructure/network/ingress.yaml, infrastructure/scripts/smoke-test.sh
=> [#221] Further improvements to the script

backend/api/admin/src/main/java/co/airy/core/api/admin/sources/google/GoogleSource.java, backend/sources/google/sender/src/main/java/co/airy/core/sources/google/services/Api.java, docs/docs/api/http.md
=> Add google admin api channel connection

docs/docusaurus.config.js
=> [#292] Configure algolia for docs.airy.co

docs/docs/api/http.md, docs/docs/sources/facebook.md, docs/docs/sources/google.md
Fixes https://github.com/airyhq/airy/issues/268
=> [#268] Google/Facebook source documentation

README.md, docs/docs/index.md
=> [#318] Docs should use the right branch

infrastructure/scripts/smoke-test.sh
=> [#231] Smoke test improvements

backend/lib/kafka/schema/src/main/java/co/airy/kafka/schema/SourceTwilio.java, backend/lib/kafka/schema/src/main/java/co/airy/kafka/schema/source/SourceFacebookEvents.java, backend/lib/kafka/schema/src/main/java/co/airy/kafka/schema/source/SourceTwilioEvents.java, docs/docs/sources/google.md, docs/docs/sources/sms-twilio.md, docs/docs/sources/twilio-source.mdx, docs/docs/sources/whatsapp-twilio.md, docs/sidebars.js, infrastructure/scripts/provision/create-topics.sh
=> [#349] Add Twilio source documentation

backend/api/admin/src/main/java/co/airy/core/api/admin/sources/facebook/FacebookApi.java
[#328] Update Subscribed Fields for Facebook Webhooks
=> [#328] Update Subscribed Fields for Facebook Webhooks

backend/api/admin/src/main/java/co/airy/core/api/admin/payload/AvailableChannelsRequestPayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/ConnectChannelRequestPayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/DeleteTagRequestPayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/DisconnectChannelRequestPayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/UpdateTagRequestPayload.java, backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ConversationByIdRequestPayload.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ConversationTagRequestPayload.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/MessageListRequestPayload.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/SendMessageRequestPayload.java, backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsTagTest.java, backend/lib/mapping/BUILD, backend/lib/mapping/src/main/java/co/airy/mapping/model/Text.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/AuthenticationRequestPayload.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/SendMessageRequestPayload.java
Fixes https://github.com/airyhq/airy/issues/322
=> [#322] Conversations.tag endpoint returns 500 on empty payload

docs/docs/sources/chat-plugin.md, frontend/chat-plugin/BUILD, frontend/chat-plugin/README.md, frontend/chat-plugin/example.html, frontend/chat-plugin/index.html, frontend/chat-plugin/src/components/websocket/index.ts
=> Add chatplugin api docs

backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/EventsRouter.java, backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/EventsRouter.java, backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/GoogleEventInfo.java, backend/sources/twilio/events-router/BUILD, backend/sources/twilio/events-router/src/main/java/co/airy/core/sources/twilio/EventsRouter.java, backend/sources/twilio/events-router/src/main/java/co/airy/core/sources/twilio/TimestampExtractor.java, backend/sources/twilio/events-router/src/main/java/co/airy/core/sources/twilio/TwilioEventInfo.java, backend/sources/twilio/events-router/src/main/java/co/airy/core/sources/twilio/TwilioInfoExtractor.java, backend/sources/twilio/events-router/src/main/resources/application.properties, backend/sources/twilio/events-router/src/test/java/co/airy/core/sources/twilio/EventsRouterTest.java
=> [#354] Add Twilio Events router, fix ingestion time bug in google source

.bazelignore, .github/workflows/main.yml, .gitignore, BUILD, docs/BUILD.bazel, scripts/lint.sh, tools/code-format/BUILD, tools/code-format/prettier.bzl
=> [#367] cleanup linting

docs/sidebars.js
=> [#369] Show release process docs in the sidebar

backend/api/admin/src/main/java/co/airy/core/api/admin/sources/twilio/TwilioSmsSource.java, backend/api/admin/src/main/java/co/airy/core/api/admin/sources/twilio/TwilioWhatsappSource.java, backend/sources/twilio/events-router/src/main/java/co/airy/core/sources/twilio/EventsRouter.java, backend/sources/twilio/events-router/src/test/java/co/airy/core/sources/twilio/EventsRouterTest.java, backend/sources/twilio/sender/src/main/java/co/airy/core/sources/twilio/Sender.java, backend/sources/twilio/sender/src/test/java/co/airy/core/sources/twilio/SendMessageTest.java, docs/docs/glossary.md, docs/docs/sources/sms-twilio.md, docs/docs/sources/whatsapp-twilio.md
=> [#352] Add Twilio channel connection

backend/lib/mapping/src/main/java/co/airy/mapping/ContentMapper.java, backend/lib/mapping/src/main/java/co/airy/mapping/SourceMapper.java, backend/lib/mapping/src/main/java/co/airy/mapping/sources/facebook/FacebookMapper.java, backend/lib/mapping/src/main/java/co/airy/mapping/sources/google/GoogleMapper.java, backend/lib/mapping/src/main/java/co/airy/mapping/sources/twilio/TwilioMapper.java, backend/lib/mapping/src/test/java/co/airy/mapping/GoogleTest.java, backend/lib/mapping/src/test/java/co/airy/mapping/TwilioTest.java
=> [#350] Twilio content mapper

frontend/chat-plugin/src/components/chat/index.tsx
=> [#388] Chat plugin text render bug fixed

README.md
=> [#394] Fix broken link in documentation

docs/docs/guidelines/contributing.md, docs/docusaurus.config.js
=> [#344] Enable copy&paste of code snippets

backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java, backend/api/communication/src/main/java/co/airy/core/api/communication/MetadataController.java, backend/avro/communication/metadata-action/src/main/java/co/airy/avro/communication/MetadataKeys.java
=> [#427] Return default contact information

docs/docs/api/http.md
=> [#370] Add conversation metadata filter docs

backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/MessageResponsePayload.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Mapper.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/MessageResponsePayload.java, docs/docs/api/http.md, docs/docs/api/websocket.md, docs/docs/sources/chat-plugin.md, frontend/chat-plugin/src/airyRenderProps/AiryMessage/index.tsx, frontend/chat-plugin/src/components/chat/index.tsx
=> [#437] Replace alignment in favor of sender type

infrastructure/scripts/lib/api.sh, infrastructure/scripts/smoke-generator.sh, infrastructure/scripts/smoke-test.sh
Usage:
```
/vagrant/scripts/smoke-generator.sh
```
or
```
CHANNELS=10 MESSAGES=10000 DELAY=0.5 /vagrant/scripts/smoke-generator.sh
```
=> [#451] Bash test messages generator

backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java, backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java, backend/api/communication/src/main/java/co/airy/core/api/communication/dto/Conversation.java, backend/api/communication/src/main/java/co/airy/core/api/communication/dto/ConversationIndex.java, backend/api/communication/src/main/java/co/airy/core/api/communication/dto/DisplayName.java, backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/DocumentMapper.java, backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/LuceneDiskStore.java, backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/LuceneProvider.java, backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/StoreChangeLogger.java
=> [#457] Improve conversations query (indexes, restoration, api)

docs/docs/api/http.md
A few initial updates to the file
=> Updates to api HTTP docs

docs/docs/guides/architecture.md
Improves the readability. It's important to keep the bullet points identical in their structure. In this case, each bullet point starts with a verb.
=> Small improvements

frontend/demo/README.md
=> [#524] remove hyperlinks

lib/java/mapping/src/main/java/co/airy/mapping/sources/google/GoogleMapper.java, lib/java/mapping/src/test/java/co/airy/mapping/GoogleTest.java
=> Added Image content model for gogle

backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/ChatController.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Stores.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/Jwt.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/dto/MessagesTreeSet.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/AuthenticationResponsePayload.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/ResumeTokenResponsePayload.java, backend/sources/chat-plugin/src/test/java/co/airy/core/chat_plugin/ChatControllerTest.java, docs/docs/sources/chat-plugin.md, infrastructure/network/ingress.yaml
=> [#527] Enable resuming of chatplugin conversations

.eslintrc, frontend/chat-plugin/src/airyRenderProps/AiryMessage/index.tsx, frontend/chat-plugin/src/components/chat/index.tsx, frontend/chat-plugin/src/components/websocket/index.ts, frontend/chat-plugin/src/defaultScript.tsx, frontend/chat-plugin/src/iframe.tsx, frontend/chat-plugin/src/routes/chat/index.tsx, infrastructure/helm-chart/charts/apps/charts/sources-chatplugin/templates/deployment.yaml
=> [#587] fix chat plugin development env

scripts/release.sh
Fixes https://github.com/airyhq/airy/issues/327
=> [#327] Introduce a release script that automates the process

lib/java/mapping/src/ts-generator/java/co/airy/ts_generator/Main.java, lib/typescript/types/content.ts
Needed so that #642 can be completed more easily
=> [#642] Update typescript content typings

frontend/chat-plugin/src/components/api/index.tsx, frontend/chat-plugin/src/components/chat/index.tsx, frontend/chat-plugin/src/components/websocket/index.ts
=> [#501] Resume conversation in chat plugin

lib/typescript/httpclient/endpoints/connectChannel.ts, lib/typescript/httpclient/endpoints/disconnectChannel.ts, lib/typescript/httpclient/endpoints/exploreChannels.ts, lib/typescript/httpclient/endpoints/listChannels.ts, lib/typescript/httpclient/endpoints/listConversations.ts, lib/typescript/httpclient/endpoints/listMessages.ts, lib/typescript/httpclient/endpoints/listTags.ts, lib/typescript/httpclient/endpoints/loginViaEmail.ts, lib/typescript/httpclient/mappers/channelMapper.ts, lib/typescript/httpclient/mappers/channelsMapper.ts, lib/typescript/httpclient/mappers/connectChannelApiMapper.ts, lib/typescript/httpclient/mappers/conversationMapper.ts, lib/typescript/httpclient/mappers/conversationsMapper.ts, lib/typescript/httpclient/mappers/disconnectChannelApiMapper.ts, lib/typescript/httpclient/mappers/messageMapper.ts, lib/typescript/httpclient/mappers/messageMapperData.ts, lib/typescript/httpclient/mappers/tagsMapper.ts, lib/typescript/httpclient/mappers/userMapper.ts
=> add mappers to ts http client lib 

infrastructure/cli/cmd/root.go, infrastructure/cli/pkg/tests/golden/cli.no-args.golden, scripts/bootstrap.sh
- Move the cli configuration to the directory `~/.airy`
- Download kubeconf file to the directory
=> [#620] Download kubeconf file

lib/java/mapping/src/main/java/co/airy/mapping/model/Content.java, lib/java/mapping/src/main/java/co/airy/mapping/model/SourceTemplate.java, lib/java/mapping/src/main/java/co/airy/mapping/sources/facebook/FacebookMapper.java, lib/java/mapping/src/test/java/co/airy/mapping/FacebookTest.java, lib/java/mapping/src/test/resources/facebook/template_generic.json
=> [#641] Add content type for source templates

backend/api/communication/src/main/java/co/airy/core/api/communication/payload/SendMessageRequestPayload.java, backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsInfoTest.java, backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java, backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsTagTest.java, backend/api/communication/src/test/java/co/airy/core/api/communication/MessagesTest.java, backend/api/communication/src/test/java/co/airy/core/api/communication/MetadataControllerTest.java, backend/api/communication/src/test/java/co/airy/core/api/communication/SendMessageControllerTest.java, backend/api/communication/src/test/java/co/airy/core/api/communication/UnreadCountTest.java, backend/api/communication/src/test/java/co/airy/core/api/communication/WebSocketControllerTest.java, backend/api/communication/src/test/java/co/airy/core/api/communication/util/Topics.java, docs/docs/api/http.md, lib/java/mapping/src/main/java/co/airy/mapping/model/SourceTemplate.java, lib/java/mapping/src/main/java/co/airy/mapping/sources/facebook/FacebookMapper.java, lib/typescript/types/content.ts
=> [#640] Enrich send message API with source template messages

backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/EventInfo.java, backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/EventsRouter.java, backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/InfoExtractor.java, backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/WebhookEvent.java, backend/sources/google/events-router/src/test/java/co/airy/core/sources/google/EventsRouterTest.java, docs/docs/api/webhook.md, lib/java/mapping/src/main/java/co/airy/mapping/sources/google/GoogleMapper.java, lib/java/mapping/src/test/java/co/airy/mapping/GoogleTest.java, lib/java/mapping/src/test/resources/google/suggestionResponse.json, lib/java/mapping/src/test/resources/google/text.json
=> [#667] Support Google suggestion responses

backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/SendMessageRequestPayload.java, backend/sources/chat-plugin/src/test/java/co/airy/core/chat_plugin/ChatControllerTest.java, backend/sources/facebook/connector/BUILD, backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/api/Api.java, backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/api/Mapper.java, backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/api/model/SendMessagePayload.java, backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/SendMessageTest.java, backend/sources/google/connector/BUILD, backend/sources/google/connector/src/main/java/co/airy/core/sources/google/Connector.java, backend/sources/google/connector/src/main/java/co/airy/core/sources/google/services/Mapper.java, backend/sources/google/connector/src/test/java/co/airy/core/sources/google/SendMessageTest.java, backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/Connector.java, backend/sources/twilio/connector/src/test/java/co/airy/core/sources/twilio/SendMessageTest.java, docs/docs/sources/chat-plugin.md, docs/docs/sources/facebook.md, frontend/chat-plugin/BUILD, frontend/chat-plugin/src/components/api/index.tsx, frontend/chat-plugin/src/components/chat/index.tsx, frontend/chat-plugin/src/components/websocket/index.ts, frontend/demo/BUILD, lib/java/mapping/src/main/java/co/airy/mapping/OutboundMapper.java, lib/java/mapping/src/test/java/co/airy/mapping/ContentMapperTest.java, lib/typescript/types/BUILD, lib/typescript/types/global.d.ts, lib/typescript/types/index.ts, tsconfig.json
=> [#644] Facebook connector sends out templates

backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java, backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/DocumentMapper.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ContactResponsePayload.java, docs/docs/api/http.md, frontend/demo/src/reducers/data/conversations/index.ts, lib/typescript/httpclient/mappers/conversationMapper.ts, lib/typescript/httpclient/model/Contact.ts, lib/typescript/httpclient/payload/ConversationPayload.ts
=> [#693] Simplify display name contact API response

docs/docs/api/websocket.md
=> [#704] Update websocket documentation

frontend/demo/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
=> [#713] Fix bug on tags list

frontend/demo/index.html, frontend/demo/src/InitializeAiryApi.ts, frontend/demo/src/env.ts
=> [#698] Use host config coming from the env

backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Connector.java, backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Stores.java
We investigated a crash on a core instance with lots of production data. Suppression is not needed so far
=> Remove suppression

backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java, backend/api/communication/src/main/java/co/airy/core/api/communication/Mapper.java, backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java, backend/api/communication/src/main/java/co/airy/core/api/communication/dto/Conversation.java, backend/api/communication/src/main/java/co/airy/core/api/communication/dto/ConversationIndex.java, backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/DocumentMapper.java, backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/ExtendedQueryParser.java, backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java, backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Stores.java
=> Fix numeric range queries

frontend/demo/src/pages/Inbox/ConversationListItem/index.tsx
=> fixed read conversation when it is active

docs/docusaurus.config.js
Until we sort out how we want to handle versioned docs
=> [#491] Do not show the edit button for docs

frontend/chat-plugin/src/airyRenderProps/AiryMessage/index.tsx, frontend/chat-plugin/src/components/chat/index.tsx, lib/typescript/types/content.ts
=> [#778] Fix display of messages in Chat Plugin

frontend/demo/src/pages/Inbox/MessageInput/index.tsx
=> [#788] Import StateModel instead of RootState

frontend/demo/BUILD, frontend/demo/src/App.tsx, frontend/demo/src/actions/channel/index.ts, frontend/demo/src/actions/conversations/index.ts, frontend/demo/src/actions/messages/index.ts, frontend/demo/src/components/AiryWebsocket/index.tsx, frontend/demo/src/reducers/data/channels/index.ts, frontend/demo/src/reducers/data/conversations/index.ts, frontend/demo/src/reducers/data/messages/index.ts, lib/typescript/httpclient/index.ts, lib/typescript/httpclient/mappers/channelMapper.ts, lib/typescript/httpclient/mappers/conversationMapper.ts, lib/typescript/httpclient/model/Conversation.ts, lib/typescript/websocketclient/BUILD, lib/typescript/websocketclient/README.md, lib/typescript/websocketclient/index.ts, lib/typescript/websocketclient/stompWrapper.ts, package.json, tsconfig.json
=> [#538] Wire websocket server to the redux store

frontend/demo/src/pages/Inbox/MessageInput/index.module.scss, frontend/demo/src/pages/Inbox/MessageInput/index.tsx, frontend/demo/src/pages/Inbox/Messenger/MessengerContainer/index.module.scss, frontend/demo/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
=> [#791] Message Input UI/Design Improvement

frontend/demo/src/pages/Inbox/Messenger/MessengerContainer/index.module.scss, frontend/demo/src/pages/Inbox/Messenger/MessengerContainer/index.tsx
=> Fix expanding message container

frontend/demo/src/pages/Inbox/MessageInput/index.tsx
=> [#813] Prevent sending empty messages

docs/docs/getting-started/quickstart.md, docs/docs/sources/introduction.md, docs/sidebars.js
=> [#819] Introduce sources introduction

frontend/ui/src/components/ResizableWindowList/index.module.scss, frontend/ui/src/components/ResizableWindowList/index.tsx
=> [#833] Bottom space in conversation list

frontend/ui/src/pages/Inbox/index.tsx, frontend/ui/src/reducers/data/conversations/index.ts
=> [#832] Merging messages when loading conversations

backend/api/communication/src/main/java/co/airy/core/api/communication/WebSocketConfig.java, backend/api/communication/src/test/java/co/airy/core/api/communication/WebSocketControllerTest.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/JwtAuthenticationFilter.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/WebSocketConfig.java, backend/sources/chat-plugin/src/test/java/co/airy/core/chat_plugin/ChatControllerTest.java, docs/docs/api/authentication.md, docs/docs/getting-started/quickstart.md, frontend/chat-plugin/src/components/api/index.tsx, frontend/chat-plugin/src/components/websocket/index.ts, lib/java/spring/auth/src/main/java/co/airy/spring/auth/JwtAuthenticationFilter.java, lib/java/spring/test/src/main/java/co/airy/spring/test/WebTestHelper.java, lib/typescript/httpclient/index.ts, lib/typescript/websocketclient/stompWrapper.ts
=> [#729] Make auth header compliant with rfc6750 (Bearer auth)

frontend/ui/src/env.ts
=> [#575] Fix window: any type definition

frontend/ui/src/components/TopBar/index.module.scss, frontend/ui/src/components/TopBar/index.tsx
=> [#834]Delete link in old inbox and css fix

backend/model/metadata/BUILD, backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataObjectMapper.java, backend/model/metadata/src/test/java/co/airy/model/metadata/ObjectMapperTest.java
=> Map metadata to object

lib/typescript/httpclient/payload/LoginViaEmailRequestPayload.ts, lib/typescript/render/components/Avatar/index.tsx, lib/typescript/render/components/Image/index.module.scss, lib/typescript/render/components/Image/index.tsx, lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx, lib/typescript/render/providers/facebook/FacebookRender.tsx, lib/typescript/render/providers/facebook/facebookModel.ts, package.json
=> [#854] Render File from Facebook

lib/typescript/render/components/RichCard/index.module.scss, lib/typescript/render/components/RichCard/index.tsx, lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx, lib/typescript/render/providers/chatplugin/chatPluginModel.ts
resolves #911 / related to #858
note: atm buttons contain external links, perhaps this would have to be fixed in the future if we want the buttons to link to another template in addition to external links
changes: 
- Title, description, and one suggestion button are optional fields
- The template is designed to have at least one image and one button
- time is removed from the component (as we will externalize this)
=> fixed rich card rendering with product requirements

lib/typescript/render/providers/facebook/FacebookRender.tsx, lib/typescript/render/providers/facebook/components/ButtonTemplate/index.module.scss, lib/typescript/render/providers/facebook/components/ButtonTemplate/index.tsx, lib/typescript/render/providers/facebook/facebookModel.ts
=> [#855] Render Button Template from Facebook

lib/typescript/render/providers/facebook/FacebookRender.tsx, lib/typescript/render/providers/facebook/components/ButtonTemplate/index.tsx, lib/typescript/render/providers/facebook/components/GenericTemplate/index.module.scss, lib/typescript/render/providers/facebook/components/GenericTemplate/index.tsx, lib/typescript/render/providers/facebook/facebookModel.ts
=> [#856] Render Generic Template from Facebook

backend/api/websocket/BUILD, backend/api/websocket/src/main/java/co/airy/core/api/websocket/Stores.java, backend/api/websocket/src/main/java/co/airy/core/api/websocket/WebSocketConfig.java, backend/api/websocket/src/main/java/co/airy/core/api/websocket/WebSocketController.java, backend/api/websocket/src/main/java/co/airy/core/api/websocket/payload/ChannelEvent.java, backend/api/websocket/src/main/java/co/airy/core/api/websocket/payload/Event.java, backend/api/websocket/src/main/java/co/airy/core/api/websocket/payload/MessageEvent.java, backend/api/websocket/src/main/java/co/airy/core/api/websocket/payload/MetadataEvent.java, backend/api/websocket/src/main/resources/application.properties, backend/api/websocket/src/test/java/co/airy/core/api/websocket/WebSocketControllerTest.java, backend/api/websocket/src/test/resources/test.properties, backend/sources/twilio/events-router/src/test/java/co/airy/core/sources/twilio/EventsRouterTest.java, docs/docs/api/websocket.md, infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/Chart.yaml, infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/templates/deployment.yaml, infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/templates/service.yaml, infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/values.yaml, infrastructure/helm-chart/templates/ingress.yaml, lib/typescript/httpclient/mappers/channelMapper.ts, lib/typescript/httpclient/payload/MessagePayload.ts
=> New Airy websocket using Airy events

docs/docs/api/endpoints/messages.md, docs/docs/api/websocket.md, docs/docs/sources/chat-plugin.md
=> [#910] Add message metadata API documentation

backend/api/admin/BUILD, backend/api/admin/src/main/java/co/airy/core/api/admin/Stores.java, backend/api/admin/src/main/java/co/airy/core/api/admin/TemplatesController.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/CreateTemplateRequestPayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/DeleteTemplateRequestPayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/GetTemplateRequestPayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/ListTemplatesRequestPayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/TemplatesResponsePayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/UpdateTemplateRequestPayload.java, backend/api/admin/src/test/java/co/airy/core/api/admin/ChannelsControllerTest.java, backend/api/admin/src/test/java/co/airy/core/api/admin/TemplatesControllerTest.java, backend/api/admin/src/test/java/co/airy/core/api/admin/WebhooksControllerTest.java, backend/api/admin/src/test/java/co/airy/core/api/config/ClientConfigControllerTest.java, backend/avro/communication/BUILD, backend/avro/communication/template.avsc, backend/model/channel/src/main/java/co/airy/model/channel/ChannelPayload.java, backend/model/template/BUILD, backend/model/template/src/main/java/co/airy/model/template/TemplatePayload.java, infrastructure/scripts/provision/create-topics.sh, lib/java/kafka/schema/src/main/java/co/airy/kafka/schema/application/ApplicationCommunicationTemplates.java
=> [#675] Add Templates Endpoints

frontend/chat-plugin/src/components/chat/index.tsx, lib/typescript/render/components/Text/index.module.scss, lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx, lib/typescript/render/shared.ts
=> [#956] Fix side problem in chatplugin source

backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/SendMessageRequestPayload.java
=> Allow any message to be sent to the chat plugin

README.md, backend/avro/README.md, docs/docs/concepts/design-principles.md, docs/docs/sources/google.md, frontend/README.md, frontend/ui/README.md, infrastructure/helm-chart/Chart.yaml, infrastructure/helm-chart/charts/apps/Chart.yaml, infrastructure/helm-chart/charts/apps/charts/api/Chart.yaml, infrastructure/helm-chart/charts/apps/charts/frontend/Chart.yaml, infrastructure/helm-chart/charts/apps/charts/sources/Chart.yaml, infrastructure/helm-chart/charts/apps/charts/webhook/Chart.yaml, infrastructure/helm-chart/charts/tools/Chart.yaml, infrastructure/scripts/provision/core.sh, infrastructure/scripts/status.sh, infrastructure/scripts/trigger/start.sh, infrastructure/scripts/trigger/stop.sh
@lucapette  I didn't find a place where Airy Core Platform was better suited than Airy Core. Let me know when you find one
=> [#975] Rename Airy Core Platform

frontend/ui/src/App.tsx, frontend/ui/src/pages/Channels/index.tsx, frontend/ui/src/pages/Inbox/index.tsx, frontend/ui/src/pages/Login/index.tsx, frontend/ui/src/pages/NotFound/index.tsx, frontend/ui/src/pages/Tags/index.tsx, frontend/ui/src/services/pageTitle.ts
=> [#849] Introduce dynamic page titles

frontend/chat-plugin/src/components/websocket/index.ts, frontend/ui/src/components/AiryWebsocket/index.tsx, lib/typescript/websocketclient/index.ts
=> [#1023] Websocket uses tls when the page is loaded via https

.eslintrc, frontend/chat-plugin/example.html, frontend/chat-plugin/src/App.tsx, frontend/chat-plugin/src/api/index.tsx, frontend/chat-plugin/src/components/chat/index.tsx, frontend/chat-plugin/src/config.ts, frontend/chat-plugin/src/defaultScript.tsx, frontend/chat-plugin/src/storage.ts, frontend/chat-plugin/src/websocket/index.ts
I refactored/moved a few things:
* everything is now `camelCase` in the chat plugin
* things that are no react components are now moved out of the
`components` directory
* added an eslint rule that warns if `snake_case` is used.
closes #1007
=> [#1007] Bug: Cookies + 2 Chat Plugins

backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/Publisher.java, backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/RedisQueue.java, backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/payload/QueueMessage.java, backend/webhook/publisher/src/test/java/co/airy/core/webhook/publisher/PublisherTest.java
follow up bugfix introduced by #998
=> [#885] Fix webhook payload

frontend/chat-plugin/src/App.module.scss, frontend/chat-plugin/src/components/chat/index.module.scss
=> [#1002] Chat Plugin Size

frontend/ui/src/pages/Inbox/ConversationsFilter/index.module.scss, frontend/ui/src/pages/Inbox/ConversationsFilter/index.tsx
=> [#842] Remove ugly border around filter icon

lib/typescript/render/BUILD, lib/typescript/render/components/RichText/index.module.scss, lib/typescript/render/components/RichText/index.tsx, lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx, package.json, yarn.lock
=> [#1038] ChatPlugin does not render RichText

backend/api/communication/src/main/java/co/airy/core/api/communication/MessagesController.java, backend/api/communication/src/main/java/co/airy/core/api/communication/MetadataController.java, backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/MessageSuggestRepliesRequestPayload.java, backend/api/communication/src/test/java/co/airy/core/api/communication/MessagesTest.java, backend/api/communication/src/test/java/co/airy/core/api/communication/MetadataControllerTest.java, backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataKeys.java, backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataObjectMapper.java, docs/docs/api/endpoints/messages.md
=> Add suggest replies endpoint 

WORKSPACE, backend/api/admin/BUILD, backend/api/auth/BUILD, backend/api/communication/BUILD, backend/api/websocket/BUILD, backend/media/BUILD, backend/sources/chat-plugin/BUILD, backend/sources/facebook/connector/BUILD, backend/sources/facebook/events-router/BUILD, backend/sources/google/connector/BUILD, backend/sources/google/events-router/BUILD, backend/sources/twilio/connector/BUILD, backend/sources/twilio/events-router/BUILD, backend/webhook/publisher/BUILD, backend/webhook/redis-worker/BUILD, frontend/chat-plugin/BUILD, frontend/ui/BUILD, infrastructure/.gitignore, infrastructure/cli/go.sum, infrastructure/controller/BUILD, infrastructure/helm-chart/BUILD, tools/build/container_release.bzl
=> [#1014] Add helm image containing the charts

frontend/chat-plugin/src/components/chat/index.module.scss, lib/typescript/render/components/Carousel/index.module.scss, lib/typescript/render/components/MessageInfoWrapper/index.module.scss, lib/typescript/render/components/RichCard/Media/index.module.scss, lib/typescript/render/components/RichCard/index.module.scss, lib/typescript/render/components/RichCard/index.tsx
=> [#1080] Change style of ChatPlugin + fix carousel

backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/ChannelsController.java, backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/payload/DisconnectChannelRequestPayload.java, backend/sources/google/connector/src/main/java/co/airy/core/sources/google/ChannelsController.java
=> [#1088] Fix missing Facebook channel disconnect

infrastructure/helm-chart/charts/prerequisites/templates/kafka.yaml, infrastructure/helm-chart/charts/prerequisites/values.yaml, infrastructure/helm-chart/charts/provisioning/Chart.yaml, infrastructure/helm-chart/charts/provisioning/templates/job-kafka.yaml, infrastructure/helm-chart/charts/provisioning/templates/kafka-create-topics.yaml, infrastructure/helm-chart/charts/provisioning/templates/scripts.yaml, infrastructure/helm-chart/charts/provisioning/values.yaml, infrastructure/scripts/provision/core.sh, infrastructure/scripts/status.sh, infrastructure/tools/topics/src/main/java/co/airy/tools/topics/Application.java, scripts/lint.sh
A Kubernetes job is provisioned with helm. The job has an init container which waits for the kafka service to be there, then executes the main job to create the topics.
=> [#1016] Create topics with k8s job

backend/api/admin/src/main/java/co/airy/core/api/admin/ChannelsController.java, docs/docs/api/endpoints/channels.md
=> [#1093] Fix image url for Facebook channel connection

README.md
- updated links
- updated copy
- shortened
=> Readme Revamp

infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/charts/facebook-connector/templates/deployment.yaml, infrastructure/helm-chart/charts/apps/charts/sources/charts/google/charts/google-connector/templates/deployment.yaml, infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/charts/twilio-connector/templates/deployment.yaml
=> [#1099] Add missing allowed origin env

docs/sidebars.js
Fixes https://github.com/airyhq/airy/issues/1117
=> [#1117] Template docs are not accessible

infrastructure/helm-chart/templates/ingress.yaml
Fixes https://github.com/airyhq/airy/issues/1124
=> [#1124] Template endpoints return 404

backend/api/admin/src/main/java/co/airy/core/api/admin/TemplatesController.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/UpdateTemplateRequestPayload.java, backend/api/admin/src/test/java/co/airy/core/api/admin/TemplatesControllerTest.java, infrastructure/helm-chart/templates/ingress.yaml
Fixes https://github.com/airyhq/airy/issues/1126
=> [#1126] /templates.info And /templates.update are returning 404

frontend/ui/nginx.conf
=> [#1132] Fix missing , in nginx

frontend/ui/src/components/TopBar/index.module.scss
=> [#1000] ConversationList scrolls over TopBar

frontend/ui/src/pages/Inbox/ConversationListHeader/index.module.scss
=> [#1142] Backbutton & search aligned

.github/workflows/main.yml, scripts/push-images.sh, tools/build/bazel_status.sh, tools/build/container_release.bzl
=> [#1174] Build the right cli version on develop

frontend/ui/src/pages/Inbox/ConversationsFilter/Popup.tsx
=> [#1101] Filtering by channel not functioning

tools/build/bazel_status.sh
=> [#1174] Follow up fix to bug introduced by PR #1177

infrastructure/cli/integration/version_test.go
=> [#1174] Follow up of the follow up of the fix

backend/api/admin/src/main/java/co/airy/core/api/admin/TemplatesController.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/CreateTemplateRequestPayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/UpdateTemplateRequestPayload.java, backend/api/admin/src/test/java/co/airy/core/api/admin/TemplatesControllerTest.java, backend/avro/communication/template.avsc, backend/model/template/src/main/java/co/airy/model/template/TemplatePayload.java, docs/docs/api/endpoints/templates.md
Fixes https://github.com/airyhq/airy/issues/1204
=> [#1204] Add sourceType to templates API

frontend/ui/src/reducers/data/messages/index.ts
=> [#1214] Duplicate messages in the redux store

infrastructure/helm-chart/templates/ingress.yaml
=> [#677] add missing ingress definition for suggest replies endpoint

docs/docs/getting-started/quickstart.md, docs/docs/sources/chatplugin/quickstart.md, frontend/chat-plugin/BUILD, infrastructure/helm-chart/templates/ingress-ui.yaml
=> [#1241] Fix chatplugin ui path collision

frontend/chat-plugin/example.html
=> [#1241] Fix chatplugin ui path collision. Follow up fix.

frontend/ui/src/components/IconChannelFilter/index.tsx, frontend/ui/src/pages/Channels/Twilio/SmsWhatsappForm.module.scss, frontend/ui/src/pages/Channels/Twilio/SmsWhatsappForm.tsx, frontend/ui/src/pages/Inbox/ConversationsFilter/Popup.module.scss, frontend/ui/src/pages/Inbox/ConversationsFilter/Popup.tsx
=> [#1236] Fixed issues with filter by channel

docs/docs/getting-started/components.md, docs/docs/getting-started/introduction.md, docs/sidebars.js
we will further improve the introduction with this #1262
=> [#1263] Airy Core Components: Move to own page

scripts/web-dev.sh
=> [#1041] follow up fix: missing quotes in web dev script

backend/api/admin/src/main/java/co/airy/core/api/admin/WebhooksController.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/GetWebhookResponse.java, backend/api/admin/src/test/java/co/airy/core/api/admin/WebhooksControllerTest.java, backend/avro/communication/webhook.avsc, backend/webhook/publisher/src/test/java/co/airy/core/webhook/publisher/PublisherTest.java, docs/docs/api/authentication.md, docs/docs/getting-started/installation/configuration.md, infrastructure/helm-chart/charts/apps/charts/api/charts/api-admin/templates/deployment.yaml, infrastructure/helm-chart/charts/apps/charts/api/charts/api-auth/templates/deployment.yaml, infrastructure/helm-chart/charts/apps/charts/api/charts/api-communication/templates/deployment.yaml, infrastructure/helm-chart/charts/apps/charts/api/charts/api-websocket/templates/deployment.yaml, infrastructure/helm-chart/charts/apps/charts/api/templates/api.yaml, infrastructure/helm-chart/charts/apps/charts/api/values.yaml, infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/charts/facebook-connector/templates/deployment.yaml, infrastructure/helm-chart/charts/apps/charts/sources/charts/google/charts/google-connector/templates/deployment.yaml, infrastructure/helm-chart/charts/apps/charts/sources/charts/twilio/charts/twilio-connector/templates/deployment.yaml, lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java, lib/java/spring/auth/src/main/java/co/airy/spring/auth/JwtAuthenticationFilter.java, lib/java/spring/auth/src/test/java/co/airy/spring/auth/JwtAuthenticationFilterTest.java
=> API key authentication

frontend/ui/src/components/ListenOutsideClick/index.tsx, frontend/ui/src/components/TopBar/index.tsx, frontend/ui/src/pages/Inbox/MessageInput/index.module.scss, frontend/ui/src/pages/Inbox/MessageInput/index.tsx, frontend/ui/src/pages/Inbox/SuggestedReplySelector/index.module.scss, frontend/ui/src/pages/Inbox/SuggestedReplySelector/index.tsx, frontend/ui/src/pages/Inbox/TemplateSelector/index.tsx, frontend/ui/src/reducers/data/messages/index.ts, lib/typescript/httpclient/model/Message.ts, lib/typescript/render/components/Carousel/index.module.scss
=> [#677] Render Suggested Replies

frontend/ui/BUILD, frontend/ui/src/components/AiryWebsocket/index.tsx, frontend/ui/src/reducers/data/conversations/index.ts, lib/typescript/httpclient/endpoints/connectChatPluginChannel.ts, lib/typescript/httpclient/endpoints/connectFacebookChannel.ts, lib/typescript/httpclient/endpoints/connectTwilioSmsChannel.ts, lib/typescript/httpclient/endpoints/connectTwilioWhatsappChannel.ts, lib/typescript/httpclient/endpoints/exploreFacebookChannels.ts, lib/typescript/httpclient/endpoints/getConversationInfo.ts, lib/typescript/httpclient/endpoints/listChannels.ts, lib/typescript/httpclient/endpoints/listConversations.ts, lib/typescript/httpclient/endpoints/updateChannel.ts, lib/typescript/websocketclient/index.ts
=> [#1306] Fix contact metadata problem

backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/ChatController.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Principal.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Stores.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/AuthConfig.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/Jwt.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/JwtAuthenticationFilter.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/payload/ResumeTokenRequestPayload.java, backend/sources/chat-plugin/src/test/java/co/airy/core/chat_plugin/ChatControllerTest.java, backend/sources/chat-plugin/src/test/resources/test.properties, docs/docs/api/authentication.md, docs/docs/api/endpoints/chatplugin.md, infrastructure/helm-chart/charts/apps/charts/api/templates/api.yaml, lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java, lib/java/spring/auth/src/test/java/co/airy/spring/auth/JwtAuthenticationFilterTest.java, lib/java/spring/web/src/main/java/co/airy/spring/web/Headers.java
=> [#1097] Allow users to fetch a chat plugin resume token

WORKSPACE
=> Follow up on webpack upgrade

lib/typescript/render/components/MessageInfoWrapper/index.module.scss
=> [#1383] Change size of message bubble

integration/ui/filter_conversation.spec.ts
=> [#1392] Cypress testing for filtering is false positive

lib/typescript/render/components/MessageInfoWrapper/index.module.scss
=> Revert "[#1383] Change size of message bubble"

backend/api/communication/src/main/java/co/airy/core/api/communication/dto/ConversationIndex.java, backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/DocumentMapper.java, backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java, backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataObjectMapper.java, backend/model/metadata/src/main/java/co/airy/model/metadata/dto/MetadataNode.java
=> [#1215] Index metadata

.prettierignore, docs/cli-doc/generate_cli_docs.go, docs/docs/cli/introduction.md, docs/docs/cli/usage.md, docs/docs/concepts/architecture.md, docs/docs/getting-started/installation/aws.md, docs/docs/getting-started/installation/configuration.md, docs/docs/getting-started/installation/introduction.md, docs/docs/getting-started/installation/minikube.md, docs/docs/getting-started/introduction.md, docs/docs/ui/quickstart.md, docs/sidebars.js, scripts/lint.sh
Fixes https://github.com/airyhq/airy/issues/1403
=>  [#1403] CLI Docs Revamp 

frontend/ui/src/pages/Inbox/ConversationsFilter/index.tsx
=> [#1450] Fix conversation counter

README.md
Added Explainer Graphs
Graphical improvements
=> Readme - now with nice graph-ical improvements

backend/api/communication/src/test/java/co/airy/core/api/communication/MetadataControllerTest.java, docs/docs/api/endpoints/metadata.md, docs/docs/concepts/metadata.md, docs/docs/getting-started/glossary.md, docs/sidebars.js
=> [#1164] Document and improve message upsert endpoint

backend/api/communication/src/main/java/co/airy/core/api/communication/SendMessageController.java, backend/api/communication/src/test/java/co/airy/core/api/communication/MessagesTest.java, backend/api/communication/src/test/java/co/airy/core/api/communication/UnreadCountTest.java, backend/api/communication/src/test/java/co/airy/core/api/communication/util/TestConversation.java, backend/api/websocket/src/test/java/co/airy/core/api/websocket/WebSocketControllerTest.java, backend/avro/communication/message.avsc, backend/media/src/test/java/co/airy/core/media/MessagesTest.java, backend/model/message/src/main/java/co/airy/model/message/MessageRepository.java, backend/model/message/src/main/java/co/airy/model/message/dto/MessageResponsePayload.java, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/ChatController.java, backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/FetchMetadataTest.java, backend/sources/facebook/connector/src/test/java/co/airy/core/sources/facebook/SendMessageTest.java, backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/MessageParser.java, backend/sources/facebook/events-router/src/test/java/co/airy/core/sources/facebook/EventsRouterTest.java, backend/sources/google/connector/src/test/java/co/airy/core/sources/google/SendMessageTest.java, backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/EventsRouter.java, backend/sources/google/events-router/src/test/java/co/airy/core/sources/google/EventsRouterTest.java, backend/sources/twilio/connector/src/test/java/co/airy/core/sources/twilio/SendMessageTest.java, backend/sources/twilio/events-router/src/main/java/co/airy/core/sources/twilio/EventsRouter.java, backend/sources/twilio/events-router/src/test/java/co/airy/core/sources/twilio/EventsRouterTest.java, backend/webhook/publisher/src/test/java/co/airy/core/webhook/publisher/PublisherTest.java, docs/docs/getting-started/glossary.md, frontend/chat-plugin/src/components/chat/index.tsx, frontend/ui/src/pages/Inbox/MessageInput/index.tsx, lib/java/mapping/src/main/java/co/airy/mapping/ContentMapper.java, lib/java/mapping/src/test/java/co/airy/mapping/ContentMapperTest.java, lib/typescript/httpclient/model/Content.ts, lib/typescript/httpclient/model/Message.ts, lib/typescript/websocketclient/payload.ts
Fixes #572 
Screenshot from the chatplugin
Screenshot from the inbox
=> [#572] Simplify senderType

docs/docs/getting-started/installation/aws.md, docs/docs/getting-started/installation/minikube.md, docs/docs/getting-started/introduction.md
=> [#1422] AWS Docs Revamp

docs/docs/cli/introduction.md
=> [#1532] Remove step 4 of airy cli installation docs

cli/pkg/cmd/create/helm.go, cli/pkg/workspace/template/airy.yaml, infrastructure/helm-chart/charts/apps/charts/media-resolver/values.yaml, infrastructure/helm-chart/values.yaml
=> [#1535] Release version uses correct app image tag

frontend/ui/src/pages/Inbox/MessageInput/index.tsx, frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx, lib/typescript/render/components/Text/index.module.scss
=> [#1540] Added return to messageBubble

airy.yaml, cli.yaml, frontend/chat-plugin/handles/index.ts, frontend/chat-plugin/src/airyRenderProps/AiryHeaderBar/index.tsx, frontend/chat-plugin/src/components/chat/index.tsx, frontend/chat-plugin/src/components/newConversation/index.tsx, integration/chat-plugin/end_conversation.spec.ts, integration/cypress.json, integration/ui/send_chatplugin_message.spec.ts
=> [#1503] Cypress test to end a conversation in chatplugin

.github/workflows/main.yml
=> fixed github variable

frontend/ui/src/pages/Channels/MainPage/index.tsx, integration/chat-plugin/end_conversation.spec.ts
=> fixed confikey chat plugin

infrastructure/helm-chart/templates/ingress.yaml
=> [#1577] /conversations.setState Returns 404

frontend/ui/src/pages/Channels/MainPage/index.module.scss, frontend/ui/src/pages/Channels/MainPage/index.tsx
=> [#1581] Prevent page from crashing when adding a channel

frontend/chat-plugin/index.ts, frontend/chat-plugin/src/App.tsx, frontend/chat-plugin/src/airyRenderProps/AiryBubble/index.tsx, frontend/chat-plugin/src/airyRenderProps/AiryHeaderBar/index.tsx, frontend/chat-plugin/src/airyRenderProps/AiryInputBar/index.tsx, frontend/chat-plugin/src/api/index.tsx, frontend/chat-plugin/src/components/chat/index.tsx, frontend/chat-plugin/src/config.ts, frontend/chat-plugin/src/defaultScript.tsx, frontend/chat-plugin/src/websocket/index.ts, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
=> [#1590] Fix api host variable injection in chatplugin

frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx, lib/typescript/render/components/Image/index.module.scss, lib/typescript/render/components/Video/index.tsx
=> [#1415] Fix Video & Image Rendering Problem

infrastructure/helm-chart/charts/apps/charts/api/templates/security.yaml
=> [#1517] Don't create a default system token

cli/pkg/cmd/create/create.go, cli/pkg/providers/aws/BUILD, cli/pkg/providers/aws/aws.go, cli/pkg/providers/minikube/minikube.go, cli/pkg/providers/provider.go, docs/docs/cli/usage.md, docs/docs/getting-started/installation/aws.md
Ability to provider `provider-config` flag and create in existing vpc:
```
airy create --provider aws --provider-cofnig vpcId=vpc-12345
```
=> [#1580] Create in existing VPC on AWS

frontend/ui/src/pages/Channels/MainPage/index.tsx, frontend/ui/src/pages/Channels/Providers/Google/GoogleBusinessMessagesRequirementsDialog/index.module.scss, frontend/ui/src/pages/Channels/Providers/Google/GoogleBusinessMessagesRequirementsDialog/index.tsx
closes #1603
- GBM modal box linked to the Google source from the docs
=> [#1603] Redirect when trying to add GBM channel

frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/ConnectNewChatPlugin.tsx
=> [#1618] Remove intermediate call to action from new chat plugin

docs/docs/sources/facebook.md, docs/docs/sources/google.md, docs/docs/sources/twilio-sources.mdx, infrastructure/helm-chart/charts/apps/charts/sources/charts/facebook/templates/deployments.yaml
Aligning config options for the sources in `airy.yaml`.
related to #1635
=> [#1635] Update docs on configuring sources

lib/typescript/components/general/Carousel/index.module.scss, lib/typescript/render/components/MessageInfoWrapper/index.module.scss
=> [#1637] fix carousels

frontend/ui/src/pages/Channels/MainPage/index.module.scss, frontend/ui/src/pages/Channels/MainPage/index.tsx, frontend/ui/src/pages/Inbox/ConversationListHeader/index.tsx, frontend/ui/src/pages/Inbox/MessageInput/index.tsx, frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.module.scss, frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.module.scss, frontend/ui/src/pages/Inbox/Messenger/index.module.scss, frontend/ui/src/pages/Inbox/index.tsx, frontend/ui/src/pages/Tags/index.module.scss, frontend/ui/src/pages/Tags/index.tsx, lib/typescript/components/general/Carousel/index.module.scss
=> [#1639] Fix conversation count

docs/docs/getting-started/installation/minikube.md
=> [#1641] Specify the required minikube version

docs/docs/getting-started/installation/configuration.md
=> [#1661] Fix token name in docs

backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/config/AuthConfig.java
=> [#1666] Fix chatplugin cors config

docs/docs/api/endpoints/google-messages-send.mdx, docs/docs/sources/google.md
=> [#1676] fix sending messages to google source

scripts/dev_cli.sh
only works on Mac :golden-paulo:
=> [#1642] Add dev cli script

frontend/ui/src/components/TopBar/index.module.scss
=> [#1696] Fix backgroundColor accountName

lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/CommonProviders.java, lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/ConfigProvider.java
=> [#1748] Add missing default redirect uri

docs/docs/sources/chatplugin/customization.md
=> [#1745] Update chat plugin customization docs 

WORKSPACE
=> [#1486] Upgrade rules_pkg and rules_docker

package.json, yarn.lock
=> [#1486] upgrade react

backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsStateTest.java, backend/sources/twilio/connector/BUILD, backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/ChannelsController.java, backend/sources/twilio/connector/src/test/java/co/airy/core/sources/twilio/SendMessageTest.java
=> [#1681] Clean phone number input

frontend/ui/src/pages/Inbox/Messenger/ConversationStatus/index.tsx, frontend/ui/src/selectors/conversations.ts
=> [#1764] Filter fixed + state header bar toggle fix

lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java, lib/java/spring/auth/src/main/java/co/airy/spring/auth/session/CookieSecurityContextRepository.java, lib/java/spring/auth/src/test/java/co/airy/spring/auth/AuthenticationTest.java, lib/java/spring/auth/src/test/java/co/airy/spring/auth/OidcTest.java, lib/typescript/httpclient/client.ts
=> Revert "[#1743] Return proper status code for unauthorized access"

lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java, lib/java/spring/auth/src/test/java/co/airy/spring/auth/OidcTest.java
=> [#1743] Permit public auth pages

frontend/ui/src/pages/Channels/ConnectedChannelsList/index.module.scss, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/ChatPluginConnect.module.scss, frontend/ui/src/pages/Channels/Providers/Facebook/Messenger/FacebookConnect.module.scss, frontend/ui/src/pages/Channels/Providers/Twilio/SMS/TwilioSmsConnect.module.scss, frontend/ui/src/pages/Channels/Providers/Twilio/TwilioConnect.module.scss, frontend/ui/src/pages/Channels/Providers/Twilio/WhatsApp/TwilioWhatsappConnect.module.scss
=> [#1809] Channels page breaks when there are too many channels 

.bazelrc, .github/workflows/labeler.yml, .github/workflows/main.yml
=> [#1342] Fix dependabot failing PRs

infrastructure/helm-chart/templates/ngrok.yaml
=> [#1843] Fix Airy core reachability

infrastructure/helm-chart/templates/ngrok.yaml
=> [#1843] Fix Airy core reachability followup

frontend/ui/src/actions/conversations/index.ts, frontend/ui/src/actions/conversationsFilter/index.ts, frontend/ui/src/pages/Inbox/ConversationList/index.tsx, frontend/ui/src/pages/Inbox/ConversationListHeader/index.tsx, frontend/ui/src/pages/Inbox/index.tsx
=> [#1838] Add call to pagination when filtering conversations

docs/docs/api/authentication.md, lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java, lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/ClientConfig.java, lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/LoginRedirect.java, lib/java/spring/auth/src/test/java/co/airy/spring/auth/OidcTest.java
=> [#1823] Improve login/logout behavior

lib/typescript/render/providers/facebook/FacebookRender.tsx
=> [#1837] improve facebook render library follow-up

docs/docs/getting-started/components.md, docs/docs/getting-started/introduction.md
changed open source to open-source
=> fix getting started-introduction

docs/docs/sources/chatplugin/installation.md, docs/docs/sources/chatplugin/overview.md, docs/docs/sources/chatplugin/quickstart.md, docs/docs/sources/debugging-twilio.mdx, docs/docs/sources/facebook.md, docs/docs/sources/google.md, docs/docs/sources/introduction.md, docs/docs/sources/sms-twilio.md, docs/docs/sources/twilio-config.mdx, docs/docs/sources/twilio-sources.mdx, docs/docs/sources/whatsapp-twilio.md, docs/docs/ui/channels.md, docs/docs/ui/inbox.md, docs/docs/ui/introduction.md, docs/docs/ui/suggestedReplies.md, docs/docs/ui/tags.md
Created several minor grammar + punctuation edits within the `Sources` and `UI` documentation.
=> [#1853] minor grammar edits sources + UI

frontend/ui/src/pages/Inbox/ConversationList/index.tsx, frontend/ui/src/pages/Inbox/NoConversations/index.tsx
=> [#1815] Added emptyState for filtered items

frontend/ui/src/pages/Inbox/ConversationListHeader/index.tsx, integration/chat-plugin/end_conversation.spec.ts, integration/chat-plugin/websocket_test.spec.ts, integration/cypress.json, integration/ui/connect_chatplugin.spec.ts, integration/ui/create_tag.spec.ts, integration/ui/filter_conversation.spec.ts, integration/ui/send_chatplugin_message.spec.ts
=> [#1733] fix  cypress tests

backend/api/communication/src/main/java/co/airy/core/api/communication/lucene/LuceneProvider.java, frontend/ui/src/actions/conversationsFilter/index.ts
=> [#1732] Fix display name search typo

backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ConversationUpdateContactRequestPayload.java, backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsUpdateTest.java, docs/docs/api/endpoints/conversations.md
=> [#1716] Edit contact information

lib/typescript/render/components/Image/index.module.scss, lib/typescript/render/components/Image/index.tsx, lib/typescript/render/providers/facebook/FacebookRender.tsx, lib/typescript/render/providers/facebook/facebookModel.ts
=> [#1887] facebook render library improvement: postback and images

frontend/ui/src/reducers/data/conversations/index.ts
=> [#1868] tagging filtered conversations doesn't work properly

backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java, backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/BeanstalkPublisher.java, backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/Publisher.java
=> [#1898] Webhook should start from latest message

backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/PaginationData.java, backend/api/communication/src/test/java/co/airy/core/api/communication/ConversationsListTest.java, docs/docs/api/endpoints/conversations.md, docs/docs/api/endpoints/introduction.md, docs/docs/api/endpoints/messages.md, frontend/ui/src/pages/Inbox/ConversationListHeader/index.tsx, frontend/ui/src/reducers/data/conversations/index.ts
=> [#1899] Remove filtered total

frontend/ui/src/App.module.scss, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.module.scss, frontend/ui/src/pages/Inbox/ConversationListHeader/index.tsx, frontend/ui/src/reducers/data/conversations/index.ts, frontend/ui/src/reducers/data/conversationsFilter/index.ts
=> [#1907] Fixed customize screen for 13' displays

lib/typescript/render/SourceMessagePreview.tsx
=> [#1913] Last message icon for image sent in Google conversation displays text

frontend/ui/src/App.module.scss
=> [#1919] Fixed min-height

README.md
=> #1956 - Fix link to installation page

frontend/ui/index.html, frontend/ui/src/pages/Inbox/MessageInput/index.module.scss, frontend/ui/src/pages/Inbox/MessageInput/index.tsx, lib/typescript/render/components/Text/index.module.scss
=> [#1967] Fixed messageInput

backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/api/Api.java
=> [#1974] Upgrade to Facebook API graph version 11

lib/typescript/render/providers/facebook/FacebookRender.tsx, lib/typescript/render/providers/facebook/facebookModel.ts
=> [#1985] Bug: Template Title not Rendering

docs/docs/changelog.md
=> [#2038] Fix broken download links on release page

.github/workflows/main.yml, WORKSPACE, frontend/ui/development.html
=> [#1819] Add Airy favicon

frontend/ui/src/pages/Inbox/MessageInput/index.tsx, frontend/ui/src/services/types/messageTypes.ts
=> [#2060] edit text templates 

frontend/ui/handles/index.ts, frontend/ui/src/pages/Inbox/MessageInput/index.tsx, frontend/ui/src/pages/Inbox/SuggestedReplySelector/index.tsx, integration/cypress.json, integration/ui/suggested_replies.spec.ts
=> [#1391] Cypress test for suggested replies 

frontend/ui/handles/index.ts, frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx, integration/cypress.json, integration/ui/display_name_edit.spec.ts, integration/ui/state_conversations.spec.ts
=> [#1916] Cypress test for display name edit

frontend/chat-plugin/src/airyRenderProps/AiryHeaderBar/index.module.scss, frontend/chat-plugin/src/airyRenderProps/AiryHeaderBar/index.tsx, frontend/chat-plugin/src/config.ts, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
=> [#2074] Added subtitle to Chatplugin

frontend/chat-plugin/BUILD, frontend/chat-plugin/README.md, frontend/chat-plugin/package.json, lib/typescript/httpclient/README.md, lib/typescript/httpclient/package.json
=> [#2069] fix http client and chat plugin packages

frontend/ui/src/reducers/data/conversations/index.ts
=> [#1702] Update conversations counter in real time

frontend/ui/src/actions/channel/index.ts, frontend/ui/src/pages/Channels/ConnectedChannelsList/index.tsx, frontend/ui/src/pages/Channels/MainPage/index.tsx, frontend/ui/src/pages/Channels/Providers/Google/GoogleBusinessMessagesRequirementsDialog/index.module.scss, frontend/ui/src/pages/Channels/Providers/Google/GoogleConnect.module.scss, frontend/ui/src/pages/Channels/Providers/Google/GoogleConnect.tsx, frontend/ui/src/pages/Channels/index.tsx, frontend/ui/src/routes/routes.ts, lib/typescript/httpclient/client.ts, lib/typescript/httpclient/src/endpoints/connectGoogleChannel.ts, lib/typescript/httpclient/src/endpoints/index.ts, lib/typescript/httpclient/src/payload/ConnectChannelGoogleRequestPayload.ts, lib/typescript/httpclient/src/payload/index.ts
=> [#661] Added possibility to connect Google via UI

frontend/ui/src/pages/Inbox/ConversationListItem/index.module.scss
=> [#2093] Fixed moving avatar in ConversationListItem

.github/ISSUE_TEMPLATE/---bug-report.md, .github/ISSUE_TEMPLATE/---feature-request.md
=> [#1970] Add issue templates

.github/dependabot.yml, backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java, backend/api/communication/src/test/java/co/airy/core/api/communication/MessagesTest.java, backend/api/communication/src/test/java/co/airy/core/api/communication/SendMessageControllerTest.java, backend/api/websocket/src/main/java/co/airy/core/api/websocket/WebSocketController.java, backend/sources/chat-plugin/BUILD, backend/sources/chat-plugin/src/main/java/co/airy/core/chat_plugin/Stores.java, backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Connector.java, backend/sources/facebook/connector/src/main/java/co/airy/core/sources/facebook/Stores.java, backend/sources/facebook/connector/src/main/resources/application.properties, backend/sources/google/connector/src/main/java/co/airy/core/sources/google/Connector.java, backend/sources/google/connector/src/main/java/co/airy/core/sources/google/Stores.java, backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/Connector.java, backend/sources/twilio/connector/src/main/java/co/airy/core/sources/twilio/Stores.java, backend/webhook/publisher/src/main/java/co/airy/core/webhook/publisher/Publisher.java
=> [#2132] Allow deleting messages

docs/docs/changelog.md
update changelog to changes from release 0.26.0
=> Release 0.26.0

backend/webhook/publisher/BUILD
=> Enable Prometheus endpoint on webhook publisher

docs/docs/changelog.md
changelog update for Release 0.26.0
=> Release 0.26.0 

backend/webhook/publisher/BUILD
=> [#2155] Add springboot actuator dep

lib/java/spring/web/src/main/java/co/airy/spring/web/filters/HttpPostLogFilter.java, lib/java/spring/web/src/main/java/co/airy/spring/web/filters/RequestLoggingConfig.java
=> [#2162] Only log post requests to kafka

cli/pkg/cmd/config/config.go, cli/pkg/cmd/create/BUILD, cli/pkg/cmd/create/create.go, cli/pkg/providers/minikube/minikube.go, docs/docs/cli/usage.md
=> [#1972] [#1598] Apply configuration after create and supress minikube download output

backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java, backend/api/communication/src/test/java/co/airy/core/api/communication/UnreadCountTest.java, docs/docs/api/endpoints/conversations.md, docs/sidebars.js, infrastructure/helm-chart/templates/ingress.yaml, lib/typescript/httpclient/src/endpoints/readConversations.ts
=> [#1211] Rename conversations.read endpoint

frontend/chat-plugin/lib/src/api/index.tsx, frontend/chat-plugin/lib/src/components/chat/index.tsx, frontend/chat-plugin/lib/src/websocket/index.ts
=> [#1805] Fix Chatplugin reconnection

frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss
=> [#2176] Set sendButton fixed Chatplugin

.github/ISSUE_TEMPLATE/---bug-report.md, frontend/chat-plugin/image/nginx.conf, scripts/release.sh
=> [#2182] release script fails if GITHUB_TOKEN env is not set

frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
=> Fix chatplugin code generator

backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/EventsRouter.java, backend/sources/google/events-router/src/main/java/co/airy/core/sources/google/WebhookEvent.java, backend/sources/google/events-router/src/test/java/co/airy/core/sources/google/EventsRouterTest.java, lib/typescript/components/general/Emoji/index.tsx, lib/typescript/components/general/index.ts, lib/typescript/render/components/Text/index.module.scss, lib/typescript/render/components/Text/index.tsx, lib/typescript/render/providers/google/GoogleRender.tsx, lib/typescript/render/providers/google/components/RequestedLiveAgent/index.module.scss, lib/typescript/render/providers/google/components/RequestedLiveAgent/index.tsx, lib/typescript/render/providers/google/googleModel.ts
=> [#2117] Ingest and render Google Business Messages requests for live agents

.bazelrc, backend/api/admin/src/main/java/co/airy/core/api/admin/WebhooksController.java, backend/api/admin/src/main/java/co/airy/core/api/config/ServiceDiscovery.java, backend/api/admin/src/main/java/co/airy/core/api/config/dto/ComponentInfo.java, backend/api/admin/src/test/java/co/airy/core/api/admin/WebhooksControllerTest.java
=> [#2140] Call to /webhooks.subscribe fails when the component is not enabled or crashing

docs/docs/concepts/release-process.md, docs/docs/sources/instagram.md, lib/typescript/httpclient/README.md
=> [#2186] Small docs fixes 

lib/typescript/render/outbound/index.ts
=> [#2215] fix instagram mapper

frontend/ui/src/pages/Inbox/Messenger/MessengerContainer/index.module.scss, frontend/ui/src/pages/Inbox/Messenger/index.module.scss
=> [#2219] fixed inbox ui overflow bug

docs/docs/changelog.md
=> fix changelog

frontend/chat-plugin/dev/development.html, frontend/chat-plugin/image/index.tsx, frontend/chat-plugin/lib/src/airyRenderProps/AiryBubble/index.module.scss, frontend/chat-plugin/lib/src/airyRenderProps/AiryHeaderBar/index.module.scss, frontend/chat-plugin/lib/src/airyRenderProps/AiryHeaderBar/index.tsx, frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss, frontend/chat-plugin/lib/src/api/index.tsx, frontend/chat-plugin/lib/src/components/chat/index.module.scss, frontend/chat-plugin/lib/src/websocket/index.ts, lib/typescript/components/message/Reaction/index.tsx
=> Chatplugin Interferes with Web

lib/typescript/components/alerts/SettingsModal/style.module.scss
=> [#2260] Fixed z-index of modal

docs/docs/sources/chatplugin/customization.md, frontend/chat-plugin/dev/config.ts, frontend/chat-plugin/lib/src/airyRenderProps/AiryHeaderBar/index.tsx, frontend/chat-plugin/lib/src/components/chat/index.tsx, frontend/chat-plugin/lib/src/config.ts
=> More configs for chatplugin + docs

frontend/chat-plugin/dev/config.ts, frontend/chat-plugin/lib/src/components/chat/index.module.scss, frontend/chat-plugin/lib/src/components/chat/index.tsx
=> Chatplugin Customize Section Not Working

docs/docs/sources/chatplugin/customization.md, frontend/chat-plugin/dev/config.ts, frontend/chat-plugin/lib/src/AiryChatPlugin.tsx, package.json, yarn.lock
=> fix docs + fix responsiveness of chatplugin

frontend/chat-plugin/lib/src/airyRenderProps/AiryHeaderBar/index.tsx, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.module.scss, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
=> Added more configs to the ui

infrastructure/helm-chart/charts/core/charts/upgrading/templates/0.29.0.yaml
- Scale down api-communication
- Wait for the consumer group to be empty
- Reset the api.CommunicationStores consumer-group
=> [#2275] Upgrade api-communication

lib/typescript/assets/images/icons/play-circle.svg, lib/typescript/dates/convert.ts, lib/typescript/render/providers/facebook/FacebookRender.tsx, lib/typescript/render/providers/facebook/components/InstagramStoryReplies/index.module.scss, lib/typescript/render/providers/facebook/components/InstagramStoryReplies/index.tsx, lib/typescript/render/providers/facebook/facebookModel.ts
closes #2227 
changes: 
- show instagram story reply 
- links to the active or, mentions that it is expired
=> [#2227] instagram source show story reply in inbox UI

frontend/ui/src/reducers/data/conversations/index.ts
=> [#2370] Fix inbox counter bug when paginating

frontend/ui/src/pages/Inbox/MessageInput/index.tsx
=> [#2358] preventing second enter when sending messages

.github/ISSUE_TEMPLATE/---docs.md, infrastructure/helm-chart/charts/core/templates/ingress.yaml, lib/java/spring/auth/src/main/java/co/airy/spring/auth/oidc/CommonProviders.java
=> [#2394] Fixes source api ingress typo

frontend/ui/src/pages/Channels/index.module.scss
=> Fix Scrolling for Channels

docs/docs/concepts/architecture.md, docs/docs/getting-started/installation/aws.md, docs/docs/getting-started/installation/configuration.md, docs/docs/guides/backup.md, docs/sidebars.js, infrastructure/tools/restore/pv.yaml, infrastructure/tools/restore/pvc.yaml
=> Improve AWS docs

lib/typescript/httpclient/BUILD, lib/typescript/httpclient/client.ts, package.json, yarn.lock
=> [#628] make library compatible with node.js

docs/docs/sources/chatplugin/customization.md, frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss, frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.tsx, frontend/chat-plugin/lib/src/components/chat/index.tsx, frontend/chat-plugin/lib/src/config.ts, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/ChatPluginConnect.module.scss, lib/typescript/assets/images/icons/paperplane.svg
=> Add more chatplugin options 

frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.tsx, frontend/chat-plugin/lib/src/components/chat/index.tsx, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
=> Added more options to the UI

backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/MessageMapper.java
=> [#2434] Fix instagram echo ingestion

cli/go.mod, cli/go.sum, cli/pkg/cmd/create/BUILD, cli/pkg/cmd/create/create.go, cli/pkg/console/BUILD, cli/pkg/console/segment.go, cli/pkg/providers/BUILD, cli/pkg/providers/aws/BUILD, cli/pkg/providers/aws/aws.go, cli/pkg/providers/minikube/BUILD, cli/pkg/providers/minikube/minikube.go, cli/pkg/providers/provider.go, cli/pkg/workspace/airy_yaml.go, docs/docs/cli/usage.md, go.mod, go.sum, go_repositories.bzl, scripts/dev_cli.sh
=> [#2423] track core installation

lib/java/spring/auth/src/main/java/co/airy/spring/auth/AuthConfig.java, lib/java/spring/auth/src/main/java/co/airy/spring/auth/session/AuthCookie.java, lib/java/spring/core/src/main/resources/default.properties, lib/typescript/httpclient/client.ts
=> [#2443] Allow for compatability with mobile login flows

backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/MessageMapper.java
=> [#2434] Fix broken instagram Facebook inbox ingestion

cli/pkg/cmd/status/status.go, cli/pkg/console/output.go, lib/go/httpclient/payloads/client_config_response_payload.go
=> [#2511] Fix Airy status command

cli/integration/version_test.go, cli/pkg/cmd/BUILD, cli/pkg/cmd/config/config.go, cli/pkg/cmd/root.go, cli/pkg/cmd/upgrade/upgrade.go, cli/pkg/workspace/init.go
Resolves #2530 exactly as described.
=> Print airy core version with version command

frontend/ui/src/pages/Inbox/ConversationList/index.tsx
=> [#2557] Fix jumping conversationlist

scripts/dev_cli.sh
because of the tracking flag
https://github.com/airyhq/airy/issues/2560
=> [#2560] Dev_cli.sh fails to apply the config 

infrastructure/terraform/demos/analytics/files/jupyter-config.yaml
=> [#2544] Include the analytics demo files in the jupyter hub

docs/docs/sources/chatplugin/customization.md, frontend/chat-plugin/dev/config.ts, frontend/chat-plugin/lib/src/AiryChatPlugin.tsx, frontend/chat-plugin/lib/src/config.ts, frontend/ui/src/assets/scss/colors.scss, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx, frontend/ui/src/pages/Inbox/Messenger/ConversationStatus/index.tsx, lib/typescript/assets/scss/colors.scss, lib/typescript/render/components/Text/index.module.scss, lib/typescript/render/components/UnknownSourceText/index.module.scss
=> Custom message colors chatplugin + Documentation

frontend/ui/src/services/types/attachmentsTypes.ts, lib/typescript/render/services/mediaAttachments.ts
=> fixed input accept formatting

frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.tsx, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.module.scss
=> fix chatplugin customization bug

frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.module.scss, frontend/ui/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx
=> [#2154] Fixed add tag behaviour

frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.module.scss, frontend/chat-plugin/lib/src/airyRenderProps/AiryInputBar/index.tsx, frontend/chat-plugin/lib/src/config.ts, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.module.scss, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
=> [#2604] Added attachment toggle for chatplugin

backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/EventsRouter.java, backend/sources/facebook/events-router/src/main/java/co/airy/core/sources/facebook/MessageMapper.java
=> [#2434] Fix instagram ingestion race condition

frontend/ui/src/AiryConfig.ts, frontend/ui/src/pages/Channels/Providers/Instagram/InstagramConnect.tsx, lib/typescript/model/Channel.ts
=> [#2637] Fix channel prefill

lib/typescript/render/SourceMessagePreview.tsx, lib/typescript/render/providers/facebook/components/InstagramStoryReplies/index.module.scss, lib/typescript/render/providers/facebook/components/InstagramStoryReplies/index.tsx
=> [#2649] ui fix instagram messages

frontend/chat-plugin/lib/src/AiryChatPlugin.tsx, frontend/chat-plugin/lib/src/airyRenderProps/AiryBubble/index.module.scss, frontend/chat-plugin/lib/src/airyRenderProps/AiryBubble/index.tsx, frontend/chat-plugin/lib/src/airyRenderProps/AiryHeaderBar/index.module.scss, frontend/chat-plugin/lib/src/components/chat/index.module.scss
=> [#2626] Chat Plugin full screen for mobile

frontend/ui/src/pages/Channels/Providers/Instagram/InstagramConnect.tsx
=> [#2676] Prefill missing inputs instagram channel

docs/README.md, docs/docs/api/webhook.md, docs/docs/getting-started/components.md
=> [#2678] Make clear distiction between inbound outbound webhook

infrastructure/helm-chart/charts/prerequisites/charts/beanstalkd/templates/configmap.yaml, infrastructure/helm-chart/charts/prerequisites/charts/beanstalkd/templates/service.yaml
https://github.com/airyhq/airy/issues/2691
=> [#2691] Beanstalk service needs a label

.github/workflows/main.yml
=> [#2667] Fix vulnerable Github action

backend/api/contacts/src/main/java/co/airy/core/contacts/Stores.java, infrastructure/helm-chart/charts/components/templates/ingress.yaml
=> [#2293] Fix contact creation

infrastructure/helm-chart/charts/tools/charts/kafka-connect/templates/deployment.yaml, infrastructure/helm-chart/charts/tools/charts/kafka-connect/templates/jmx-configmap.yaml, infrastructure/helm-chart/charts/tools/charts/kafka-connect/templates/service.yaml, infrastructure/helm-chart/charts/tools/charts/kafka-connect/values.yaml
https://github.com/airyhq/airy/issues/2699
=> [#2699] Kafka Connect is not activatable with Helm

docs/docs/getting-started/installation/helm.md
closes https://github.com/airyhq/airy/issues/2651
=> [#2651] Helm installation tabItem is swapped

frontend/chat-plugin/lib/src/AiryChatPlugin.tsx, frontend/chat-plugin/lib/src/airyRenderProps/AiryBubble/index.tsx, frontend/chat-plugin/lib/src/components/chat/index.tsx, frontend/chat-plugin/lib/src/config.ts, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx
=> [#2577] Notification Badge Chatplugin

frontend/chat-plugin/lib/src/AiryChatPlugin.tsx
=> [#2697] Fix Chatplugin Cutting in Web Browser

frontend/ui/src/pages/Inbox/MessageInput/InputOptions.tsx
=> [#2684] Fix refresh inbox

infrastructure/helm-chart/charts/tools/charts/akhq/templates/configmap.yaml
=> [#2718] Fix schema registry url

backend/api/admin/BUILD, backend/api/admin/src/main/java/co/airy/core/api/admin/Stores.java, backend/api/admin/src/main/java/co/airy/core/api/admin/TimestampExtractor.java, backend/api/admin/src/main/java/co/airy/core/api/admin/UsersController.java, backend/api/admin/src/main/java/co/airy/core/api/admin/dto/LogWithTimestamp.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/ListUsersResponsePayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/PaginationData.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/UserResponsePayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/UsersListRequestPayload.java, backend/api/admin/src/test/java/co/airy/core/api/admin/ChannelsControllerTest.java, backend/api/admin/src/test/java/co/airy/core/api/admin/TagsControllerTest.java, backend/api/admin/src/test/java/co/airy/core/api/admin/TemplatesControllerTest.java, backend/api/admin/src/test/java/co/airy/core/api/admin/UsersControllerTest.java, backend/api/admin/src/test/java/co/airy/core/api/admin/WebhooksControllerTest.java, backend/api/admin/src/test/java/co/airy/core/api/admin/util/Topics.java, backend/api/admin/src/test/java/co/airy/core/api/config/ClientConfigControllerTest.java, backend/avro/BUILD, backend/avro/user.avsc, docs/docs/api/endpoints/users.md, docs/docs/getting-started/glossary.md, docs/sidebars.js, infrastructure/helm-chart/charts/components/templates/api/admin/deployment.yaml, infrastructure/helm-chart/charts/components/templates/ingress.yaml, infrastructure/helm-chart/templates/provisioning/kafka-create-topics.yaml, lib/java/kafka/schema/src/main/java/co/airy/kafka/schema/application/ApplicationCommunicationUsers.java, lib/java/spring/web/src/main/java/co/airy/spring/web/filters/HttpPostLogFilter.java
=> [#2646] Expose users via list api

infrastructure/helm-chart/charts/components/charts/sources/charts/viber/Chart.yaml
=> [#2724] Fix incorrect imageTag for viber

lib/typescript/components/BUILD, lib/typescript/components/general/Carousel/index.tsx
=> [#2640] Carousels not scrolling in small sizes

backend/api/contacts/src/main/java/co/airy/core/contacts/ContactsController.java, backend/api/contacts/src/main/java/co/airy/core/contacts/Stores.java, backend/api/contacts/src/main/java/co/airy/core/contacts/payload/CreateContactPayload.java, backend/api/contacts/src/test/java/co/airy/core/contacts/ImportContactsTest.java, backend/api/contacts/src/test/resources/test.properties
=> [#2693] contacts import endpoint

backend/api/contacts/src/main/java/co/airy/core/contacts/ContactsController.java, backend/api/contacts/src/main/java/co/airy/core/contacts/Stores.java, backend/api/contacts/src/main/java/co/airy/core/contacts/dto/Contact.java, backend/api/contacts/src/main/java/co/airy/core/contacts/payload/DeleteContactPayload.java, backend/api/contacts/src/test/java/co/airy/core/contacts/DeleteContactTest.java, backend/api/contacts/src/test/java/co/airy/core/contacts/ImportContactsTest.java, backend/api/contacts/src/test/resources/test.properties
=> [#2693] contacts service delete endpoint

.gitignore, infrastructure/.gitignore
=> [#2737] Added Airy config files to gitignore

backend/api/communication/src/main/java/co/airy/core/api/communication/ConversationsController.java, backend/api/communication/src/main/java/co/airy/core/api/communication/Stores.java
=> [#2745] conversations.refetch endpoint

docs/docs/api/contacts.md, docs/docs/api/endpoints/conversations.md
=> [#2693] Docs/2693 contacts service endpoins

frontend/chat-plugin/lib/src/components/chat/index.tsx
=> [#2715] Fixed notification badge after reload

backend/api/contacts/src/main/java/co/airy/core/contacts/Stores.java, lib/java/kafka/streams/src/main/java/co/airy/kafka/streams/KafkaStreamsWrapper.java
closes #2764 
There where two issues
* When the stream is not ready
* Some messages are empty (null)
=> [#2764] Bug null pointer exception on api contacts service

frontend/ui/src/httpClient.ts, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/ChatPluginConnect.tsx
=> [#2768] Make hostname optional for frontend-ui 

frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.module.scss, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/CustomiseSection.tsx, frontend/ui/src/pages/Channels/Providers/Airy/ChatPlugin/sections/EditChatPlugin.tsx
=> [#2769] Added custom host url

.gitignore, backend/api/contacts/src/main/java/co/airy/core/contacts/ContactsController.java, backend/api/contacts/src/main/java/co/airy/core/contacts/dto/Contact.java, backend/api/contacts/src/main/java/co/airy/core/contacts/payload/ContactWithMergeHistoryResponsePayload.java, backend/api/contacts/src/main/java/co/airy/core/contacts/payload/MergeContactsRequestPayload.java, backend/api/contacts/src/test/java/co/airy/core/contacts/MergeContactsTest.java, docs/docs/api/contacts.md
=> [#2693] contacts merge endpoint

frontend/chat-plugin/lib/src/components/chat/index.tsx, frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx, lib/typescript/components/message/MessageInfoWrapper/index.module.scss, lib/typescript/components/message/MessageInfoWrapper/index.tsx, lib/typescript/model/Message.ts
=> [#2641] Internally display message sender 

backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java, backend/media/src/test/java/co/airy/core/media/services/MediaUploadTest.java
=> [#2742] list objects in s3 bucket

lib/typescript/components/message/MessageInfoWrapper/index.module.scss, lib/typescript/components/message/MessageInfoWrapper/index.tsx, lib/typescript/render/SourceMessagePreview.tsx, lib/typescript/render/providers/facebook/components/InstagramShare/index.module.scss, lib/typescript/render/providers/facebook/components/InstagramShare/index.tsx, yarn.lock
closes #2766 
also fixed styling for IG share and message sender name
=> [#2766] ReactMarkdown error

backend/api/contacts/src/main/java/co/airy/core/contacts/ContactsController.java, backend/api/contacts/src/main/java/co/airy/core/contacts/dto/Contact.java, backend/api/contacts/src/main/java/co/airy/core/contacts/payload/ImportContactsResponsePayload.java, backend/api/contacts/src/main/java/co/airy/core/contacts/payload/MergeContactsResponsePayload.java, backend/api/contacts/src/test/java/co/airy/core/contacts/ImportContactsTest.java, backend/api/contacts/src/test/java/co/airy/core/contacts/MergeContactsTest.java, docs/docs/api/contacts-response-payload.md, docs/docs/api/contacts.md, infrastructure/helm-chart/charts/components/charts/api/charts/api-contacts/templates/deployment.yaml
=> [#2791] Contacts service should be off by default

WORKSPACE
=> [#2827] Fix bug in the chatplugin dev environment

infrastructure/helm-chart/charts/ingress-controller/templates/letsencrypt.yaml
=> [#2612] Update ClusterIssuer resource

infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/templates/poddisruptionbudget.yaml
=> [#2602] Upgrade PodDisruptionBudget resource

lib/typescript/render/providers/facebook/FacebookRender.tsx, lib/typescript/render/providers/facebook/components/Buttons/index.tsx, lib/typescript/render/providers/facebook/facebookModel.ts
=> [#2826] Added instagram echo payload to render library

infrastructure/helm-chart/charts/components/charts/api/charts/api-contacts/templates/deployment.yaml
=> [#2836] Disable api-contacts by default

backend/api/admin/src/main/java/co/airy/core/api/admin/WebhooksController.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/WebhookListPayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/WebhookListResponsePayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/WebhookUpdatePayload.java, backend/api/admin/src/test/java/co/airy/core/api/admin/WebhooksControllerTest.java, docs/docs/api/webhook.md
=> [#2722] Webhook subscription editable and resubscribable

frontend/chat-plugin/lib/src/AiryChatPlugin.tsx
=> [#2877] Fixed wrong chatplugin font

docs/docs/guides/backup.md, docs/docs/guides/component-reset.md, docs/sidebars.js
=> [#2909] Fix restore from backup inconsistencies

frontend/chat-plugin/lib/src/components/chat/index.module.scss, frontend/ui/src/pages/Inbox/MessageInput/AudioRecording/WaveformAudio.tsx
=> [#2920] UI fixes

backend/api/communication/src/main/java/co/airy/core/api/communication/SendMessageController.java, backend/api/communication/src/main/java/co/airy/core/api/communication/payload/ResendMessageRequestPayload.java, backend/api/communication/src/test/java/co/airy/core/api/communication/SendMessageControllerTest.java, backend/model/message/src/main/java/co/airy/model/message/MessageRepository.java, docs/docs/api/endpoints/messages.md
=> [#2918] Resend messages

WORKSPACE, package.json, yarn.lock
=> [#2774] Fix: point staging from UI local

cli/pkg/cmd/create/create.go, cli/pkg/providers/aws/aws.go, cli/pkg/providers/minikube/minikube.go
Also added a dashboard to see all events filtered by user id [here](https://dashboard.airy.co/question/210)
=> [#248] userid for all telemetry events

infrastructure/terraform/modules/core/main.tf, infrastructure/terraform/modules/core/variables.tf
=> Add prerequisite property overrides

.github/workflows/release-drafter.yml, docs/docs/concepts/release-process.md, scripts/release.sh
=> [#2932] Fix the Changelog creation

infrastructure/helm-chart/charts/prerequisites/charts/kafka/Chart.yaml, infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/kafka/templates/_helpers.tpl, infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/kafka/templates/statefulset.yaml, infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/kafka/values.yaml, infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/Chart.yaml, infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/templates/_helpers.tpl, infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/templates/headless-service.yaml, infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/templates/poddisruptionbudget.yaml, infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/templates/service.yaml, infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/templates/statefulset.yaml, infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/zookeeper/values.yaml, infrastructure/helm-chart/templates/config/kafka.yaml, infrastructure/helm-chart/templates/provisioning/job-kafka.yaml, infrastructure/helm-chart/templates/provisioning/kafka-create-topics.yaml, infrastructure/helm-chart/values.yaml, infrastructure/images/kafka/Dockerfile, infrastructure/images/kafka/Makefile, infrastructure/images/kafka/config/server.properties, infrastructure/images/kafka/config/zookeeper.properties, infrastructure/images/kafka/scripts/configure-kafka.sh, infrastructure/images/kafka/scripts/configure-zookeeper.sh, infrastructure/images/kafka/scripts/entrypoint.sh, infrastructure/terraform/main/files/defaultResourceLimits.yaml, infrastructure/tools/topics/src/main/java/co/airy/tools/topics/Application.java
=> Revert "Upgrade to Kafka 3.1.0"

frontend/ui/src/components/TopBar/index.module.scss, frontend/ui/src/components/TopBar/index.tsx
=> [#3014] Added navigation to Control-Center from Inbox

infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-control-center/Chart.yaml, infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-control-center/templates/deployment.yaml, infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-control-center/templates/ingress.yaml, infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-control-center/templates/service.yaml, infrastructure/helm-chart/charts/components/charts/frontend/charts/frontend-control-center/values.yaml
=> Deploy the control center

frontend/README.md, frontend/ui/src/pages/Inbox/Messenger/MessageList/index.module.scss, frontend/ui/src/pages/Inbox/Messenger/MessageList/index.tsx, lib/typescript/components/general/AudioClip/index.module.scss, lib/typescript/components/general/Carousel/index.module.scss, lib/typescript/components/general/Carousel/index.tsx, lib/typescript/components/message/MessageInfo/index.module.scss, lib/typescript/components/message/MessageInfo/index.tsx, lib/typescript/components/message/MessageWrapper/MessageContainer/index.module.scss, lib/typescript/components/message/MessageWrapper/MessageContainer/index.tsx, lib/typescript/components/message/MessageWrapper/index.module.scss, lib/typescript/components/message/MessageWrapper/index.tsx, lib/typescript/render/providers/google/components/Suggestions/index.module.scss, lib/typescript/render/providers/google/components/Suggestions/index.tsx
closes #3027 
closes #3035 
closes #3045
=> [#3027] carousel template bug

WORKSPACE, backend/api/admin/src/main/java/co/airy/core/api/config/ClientConfigController.java, backend/api/admin/src/main/java/co/airy/core/api/config/payload/ClientConfigResponsePayload.java, backend/api/admin/src/test/java/co/airy/core/api/config/ClientConfigControllerTest.java, docs/docs/api/endpoints/client-config.md, lib/typescript/model/Config.ts, tools/build/springboot.bzl
=> [#3023] Return cluster version on client.config endpoint

frontend/control-center/src/App.tsx, frontend/control-center/src/components/ChannelAvatar/index.tsx, frontend/control-center/src/components/Sidebar/index.tsx, frontend/control-center/src/components/TopBar/index.module.scss, frontend/control-center/src/pages/Catalog/CatalogItemList.tsx, frontend/control-center/src/pages/Catalog/index.module.scss, frontend/control-center/src/pages/Catalog/index.tsx, frontend/control-center/src/pages/Channels/ChannelCard/index.module.scss, frontend/control-center/src/pages/Channels/ChannelCard/index.tsx, frontend/control-center/src/pages/Channels/index.tsx, frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx, frontend/control-center/src/pages/Status/ComponentListItem/index.module.scss, frontend/control-center/src/pages/Status/ComponentListItem/index.tsx, frontend/control-center/src/pages/Status/index.module.scss, frontend/control-center/src/routes/routes.ts, frontend/control-center/src/services/format.ts, lib/typescript/assets/scss/fonts.scss, lib/typescript/components/inputs/Toggle/index.tsx, lib/typescript/components/inputs/Toggle/style.module.scss, lib/typescript/model/Source.ts
closes #3058 
closes #3033 
**Changes:**
- fixes for components status (animation for collapsible)
- function to figure out programmatically component and source name 
- version fix 
- catalog revamp v3: installed & not installed
=> [#3058] components status follow up

cli/pkg/providers/minikube/minikube.go, docs/docs/getting-started/installation/helm.md, docs/docs/getting-started/installation/minikube.md
=> Revert "[#2886] Overwrite minikube driver"

backend/api/admin/src/main/java/co/airy/core/api/admin/WebhooksController.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/WebhookListPayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/WebhookSubscribePayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/WebhookUpdatePayload.java, backend/api/admin/src/test/java/co/airy/core/api/admin/WebhooksControllerTest.java, backend/avro/webhook.avsc, backend/webhook/consumer/src/test/java/co/airy/core/webhook/consumer/ConsumerTest.java, backend/webhook/publisher/src/test/java/co/airy/core/webhook/publisher/PublisherTest.java
=> [#3092] Adding name to webhooks

backend/api/admin/src/main/java/co/airy/core/api/admin/WebhooksController.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/WebhookListPayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/WebhookSubscribePayload.java, backend/api/admin/src/main/java/co/airy/core/api/admin/payload/WebhookUpdatePayload.java, backend/api/admin/src/test/java/co/airy/core/api/admin/WebhooksControllerTest.java, backend/avro/webhook.avsc, backend/webhook/consumer/src/test/java/co/airy/core/webhook/consumer/ConsumerTest.java, backend/webhook/publisher/src/test/java/co/airy/core/webhook/publisher/PublisherTest.java
=> [#3109] Make name optional webhook

frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/ContactDetails/index.module.scss, frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/ContactDetails/index.tsx, infrastructure/helm-chart/BUILD, infrastructure/helm-chart/charts/ingress-controller/BUILD, infrastructure/helm-chart/charts/prerequisites/charts/beanstalkd/BUILD, infrastructure/helm-chart/charts/prerequisites/charts/kafka/BUILD, infrastructure/helm-chart/charts/tools/charts/akhq/BUILD, infrastructure/helm-chart/charts/tools/charts/kafka-connect/BUILD, lib/typescript/components/general/ConnectorAvatar/index.module.scss, lib/typescript/components/general/ConnectorAvatar/index.tsx, lib/typescript/components/general/index.ts
=> [#3073] show available conversation for same contact

docs/docs/api/webhook.md
=> [#3123] Update docs for webhooks

frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/ContactDetails/index.tsx
=> [#3141] conversations for contacts fix

frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx, frontend/control-center/src/pages/Status/ComponentListItem/index.module.scss, frontend/control-center/src/pages/Status/index.tsx
=> [#3144] Show just enabled components

lib/typescript/components/inputs/Toggle/index.tsx
=> [#3163] darkmode follow-up 

frontend/inbox/src/components/Sidebar/index.module.scss, frontend/inbox/src/components/Sidebar/index.tsx, frontend/inbox/src/pages/Inbox/Messenger/index.module.scss, frontend/inbox/src/pages/Tags/index.module.scss
=> [#3066] New design sidebar inbox

docs/docs/concepts/release-process.md
=> [#3184] Update release notes with testing

frontend/control-center/src/components/SourceInfo/index.tsx, frontend/control-center/src/pages/Connectors/ChannelCard/index.tsx, frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx, frontend/inbox/handles/index.ts, frontend/inbox/src/pages/Inbox/Messenger/MessageList/index.tsx, integration/chat-plugin/websocket_test.spec.ts, integration/cypress.json, integration/ui/connect_chatplugin.spec.ts, integration/ui/contact_edit.spec.ts, integration/ui/create_tag.spec.ts, integration/ui/display_name_edit.spec.ts, integration/ui/filter_conversation.spec.ts, integration/ui/send_chatplugin_message.spec.ts, integration/ui/state_conversations.spec.ts, integration/ui/suggested_replies.spec.ts
=> [#3185] update cypress tests

backend/api/contacts/src/main/java/co/airy/core/contacts/ContactsController.java
=> [#3234] Sort contacts alphabetically

frontend/control-center/src/components/Sidebar/index.tsx, frontend/control-center/src/components/TopBar/index.tsx, frontend/inbox/src/App.tsx, frontend/inbox/src/components/Sidebar/index.tsx, lib/typescript/model/Config.ts
=> [#3030] Added enabled service component check

frontend/control-center/src/components/Sidebar/index.module.scss, frontend/control-center/src/components/Sidebar/index.tsx, frontend/inbox/src/components/Sidebar/index.module.scss, frontend/inbox/src/components/Sidebar/index.tsx
=> [#3241] Fixed staging crashing 

lib/typescript/components/inputs/Toggle/index.tsx
=> [#3227] darkmode fix on safari

frontend/control-center/src/components/Sidebar/index.module.scss, frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx, frontend/control-center/src/pages/Status/ComponentListItem/index.module.scss, frontend/control-center/src/pages/Status/ComponentListItem/index.tsx
closes #3228 
closes #3231 
- Control Center sidebar fix 
- Status page broken on Safari fix
=> [#3228] control center fix status view

cli/pkg/cmd/create/create.go, cli/pkg/providers/aws/kubeConfigTemplate.yaml, docs/docs/cli/usage.md, scripts/dev_cli.sh
=> [#3258] Fix airy create on AWS

docs/docs/getting-started/installation/minikube.md
=> [#3279] Clarifications to minikube install

infrastructure/controller/pkg/endpoints/components_get.go, lib/go/k8s/configmaps.go
=> Fix/3343 components.get does not responds with all compoenents

infrastructure/terraform/modules/aws_eks/outputs.tf, infrastructure/terraform/modules/aws_eks/variables.tf, infrastructure/terraform/modules/core/main.tf, infrastructure/terraform/modules/core/outputs.tf
Related to the new architecture for `airy install`. Pushing module changes first to test the remote modules.
=> [#3334] Terraform module improvements

frontend/control-center/src/pages/Webhooks/EmptyState/index.module.scss, frontend/control-center/src/pages/Webhooks/EmptyState/index.tsx, frontend/control-center/src/pages/Webhooks/index.tsx, lib/typescript/components/wrapper/ContentWrapper/index.module.scss, lib/typescript/components/wrapper/ContentWrapper/index.tsx, lib/typescript/translations/translations.ts
=> [#3315] Added webhooks emptyState

frontend/control-center/src/pages/Connectors/ConnectorConfig/index.module.scss, frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/sections/CustomiseSection/ColorSection/index.module.scss, frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/sections/CustomiseSection/CustomiseSection.module.scss, frontend/control-center/src/pages/Webhooks/SubscriptionModal/index.tsx, frontend/inbox/src/pages/Tags/TableRow.tsx, frontend/inbox/src/pages/Tags/index.module.scss, frontend/inbox/src/pages/Tags/index.tsx, lib/typescript/components/cta/Button/style.module.scss, lib/typescript/components/inputs/Input/style.module.scss, lib/typescript/model/Tag.ts, lib/typescript/translations/translations.ts, yarn.lock
=> [#3305] Added translations to webhooks and tags

frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx, frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/ChatPluginConnect.tsx
closes #3426 
**Changes** 
- fix back error bug 
- fix refresh channels list bug
=> [#3426] Back error on Connectors view 

frontend/control-center/src/pages/Connectors/ConnectNewForm/index.tsx, frontend/control-center/src/pages/Connectors/Providers/Dialogflow/ConnectNewDialogflow.tsx, frontend/control-center/src/pages/Connectors/Providers/Zendesk/ConnectNewZendesk.tsx, frontend/control-center/src/pages/Connectors/Providers/Zendesk/index.module.scss, frontend/control-center/src/pages/Connectors/RestartPopUp/index.module.scss, frontend/control-center/src/pages/Connectors/RestartPopUp/index.tsx, frontend/control-center/src/pages/Connectors/index.module.scss, frontend/control-center/src/pages/Connectors/index.tsx, lib/typescript/components/alerts/SettingsModal/index.tsx, lib/typescript/translations/translations.ts
=> [#3388] Restart button to apply component config

frontend/control-center/src/pages/Catalog/index.tsx, frontend/control-center/src/pages/Status/index.tsx
=> [#3449] catalog components fix

frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx, frontend/control-center/src/pages/Connectors/InfoCard/index.module.scss, lib/typescript/components/inputs/Input/index.tsx, lib/typescript/components/inputs/Input/style.module.scss, package.json, yarn.lock
=> [#3458] Zendesk configure update name error

frontend/control-center/src/actions/catalog/index.ts, frontend/control-center/src/components/SourceInfo/index.tsx, frontend/control-center/src/pages/Connectors/ConnectNewForm/index.tsx, frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx, frontend/control-center/src/pages/Connectors/Providers/Dialogflow/ConnectNewDialogflow.tsx, frontend/control-center/src/pages/Connectors/Providers/Salesforce/ConnectNewSalesforce.tsx, frontend/control-center/src/pages/Connectors/Providers/Zendesk/ConnectNewZendesk.tsx, frontend/control-center/src/pages/Connectors/RestartPopUp/index.tsx, frontend/control-center/src/pages/Connectors/index.tsx, frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx, frontend/inbox/handles/index.ts
closes #3465 
closes #3459
closes #3460
=> [#3465] status view enable button error when component is not configured

infrastructure/helm-chart/templates/provisioning/job-kafka.yaml, infrastructure/helm-chart/templates/provisioning/kafka-create-topics.yaml, infrastructure/tools/topics/src/main/java/co/airy/tools/topics/Application.java
=> [#3096] Use jaas for creating topics

docs/docs/getting-started/installation/helm.md, docs/docs/getting-started/upgrade.md
=> [#3511] Update helm repo before install or upgrade

docs/docs/guides/contributing.md
=> [#3373] Document how we work with rules_go, gazelle, and update-deps

cli/integration/golden/cli.no-args.golden, cli/pkg/cmd/BUILD, cli/pkg/cmd/config/config.go, cli/pkg/cmd/login/BUILD, cli/pkg/cmd/login/login.go, cli/pkg/cmd/root.go, cli/pkg/cmd/status/status.go, docs/docs/cli/usage.md, lib/go/httpclient/httpclient.go
=> [#2755] Add an "airy login" command to the CLI

backend/sources/whatsapp/connector/BUILD, backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/ChannelsController.java, backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/Connector.java, backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/Stores.java, backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/WebhookController.java, backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/api/Api.java, backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/api/ApiException.java, backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/api/model/LongLivingUserAccessToken.java, backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/dto/Conversation.java, backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/dto/SendMessageRequest.java, backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/payload/ConnectChannelRequestPayload.java, backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/payload/DisconnectChannelRequestPayload.java, backend/sources/whatsapp/connector/src/test/java/co/airy/core/sources/whatsapp/ChannelsControllerTest.java, backend/sources/whatsapp/connector/src/test/resources/test.properties, docs/docs/api/endpoints/channels.md, docs/docs/api/endpoints/components.md, docs/docs/api/endpoints/connect-whatsapp.mdx, docs/docs/sources/whatsapp-cloud.md, docs/sidebars.js, infrastructure/helm-chart/charts/components/charts/sources/charts/whatsapp/Chart.yaml, infrastructure/helm-chart/charts/components/charts/sources/charts/whatsapp/templates/deployments.yaml, infrastructure/helm-chart/charts/components/charts/sources/charts/whatsapp/templates/service.yaml, infrastructure/helm-chart/charts/components/charts/sources/charts/whatsapp/values.yaml, infrastructure/helm-chart/charts/components/templates/ingress.yaml, infrastructure/helm-chart/charts/ingress-controller/templates/ngrok.yaml, infrastructure/helm-chart/templates/provisioning/kafka-create-topics.yaml, lib/java/kafka/schema/src/main/java/co/airy/kafka/schema/source/SourceWhatsappEvents.java
=> [#3533] Connect whatsapp channels

infrastructure/controller/pkg/endpoints/components_update.go, lib/go/k8s/configmaps.go
=> [#3530] airy controller component name mapping

cli/pkg/providers/minikube/minikube.go, docs/docs/changelog.md, docs/docs/getting-started/installation/helm.md, docs/sidebars.js, infrastructure/helm-chart/templates/config/kafka.yaml, infrastructure/helm-chart/templates/provisioning/kafka-create-topics.yaml, infrastructure/helm-chart/values.yaml, infrastructure/tools/topics/src/main/java/co/airy/tools/topics/Application.java, jaas.config, lib/go/config/airy_yaml.go, lib/go/config/kafka.go, lib/java/spring/kafka/streams/src/main/resources/kafka-streams.properties, tmp.yaml, tmp2.yaml
=> Hotfix: Airy with custom Kafka

backend/sources/api/helm/templates/deployment.yaml
=> [#3603] Fix integration-source-api helm code

frontend/control-center/src/App.module.scss, frontend/control-center/src/pages/Catalog/index.tsx, frontend/control-center/src/pages/Connectors/ConnectedChannelsList/ChannelsListItem/index.module.scss, frontend/control-center/src/pages/Connectors/ConnectedChannelsList/ChannelsListItem/index.tsx, frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.module.scss, frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx, frontend/control-center/src/pages/Connectors/ConnectorConfig/index.module.scss, frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx, frontend/control-center/src/pages/Connectors/index.tsx, lib/typescript/components/general/Pagination/index.tsx, lib/typescript/components/wrapper/ContentWrapper/index.module.scss, lib/typescript/model/Screen.ts, lib/typescript/model/index.ts, lib/typescript/translations/translations.ts
=> [#3591] Enhancement enable/disable

frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.module.scss
=> [#3606] logo fix

frontend/control-center/src/components/SourceInfo/index.tsx, frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.module.scss, frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.module.scss, frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx, frontend/control-center/src/pages/Connectors/ConnectorConfig/index.module.scss, frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/ChatPluginConnect.module.scss, frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/ChatPluginConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/sections/CustomiseSection/CustomiseSection.tsx, lib/typescript/components/wrapper/ContentWrapper/index.module.scss, lib/typescript/translations/translations.ts
=> [#3605] Fix connectors connected channels

backend/model/metadata/src/main/java/co/airy/model/metadata/MetadataKeys.java, backend/sources/facebook/events-router/src/test/java/co/airy/core/sources/facebook/EventsRouterTest.java, backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/ChannelsController.java, backend/sources/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/payload/ConnectChannelRequestPayload.java, backend/sources/whatsapp/connector/src/test/java/co/airy/core/sources/whatsapp/ChannelsControllerTest.java, backend/sources/whatsapp/events-router/BUILD, backend/sources/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/EventsRouter.java, backend/sources/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/MessageMapper.java, backend/sources/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/NotAMessageException.java, backend/sources/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/dto/Event.java, backend/sources/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/model/Value.java, backend/sources/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/model/WebhookEntry.java, backend/sources/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/model/WebhookEvent.java, backend/sources/whatsapp/events-router/src/test/java/co/airy/core/sources/whatsapp/EventsRouterTest.java, backend/sources/whatsapp/events-router/src/test/resources/image.json, backend/sources/whatsapp/events-router/src/test/resources/status.json, backend/sources/whatsapp/events-router/src/test/resources/test.properties, backend/sources/whatsapp/events-router/src/test/resources/text.json, backend/sources/whatsapp/helm/templates/deployments.yaml, docs/docs/api/endpoints/connect-whatsapp.mdx, docs/docs/concepts/release-process.md, docs/docs/sources/whatsapp-cloud.md, tools/build/npm/templates/deploy.py
=> [#3534] Whatsapp: Receive messages

frontend/inbox/src/components/IconChannel/index.tsx, frontend/inbox/src/pages/Inbox/Messenger/MessageList/index.tsx, lib/typescript/model/Source.ts, lib/typescript/render/SourceMessage.tsx, lib/typescript/render/SourceMessagePreview.tsx, lib/typescript/render/outbound/index.ts, lib/typescript/render/outbound/whatsapp.ts
=> [#3634] Support whatsApp source in the render library

frontend/control-center/src/pages/Status/index.module.scss, frontend/control-center/src/pages/Status/index.tsx
=> [#3638] Added last refresh on Status page

frontend/control-center/src/pages/Connectors/ConfigureConnector/index.tsx, frontend/control-center/src/pages/Connectors/Providers/Dialogflow/DialogflowConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/Facebook/Messenger/FacebookConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/Google/GoogleConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/Instagram/InstagramConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/Rasa/RasaConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/Salesforce/ConnectNewSalesforce.tsx, frontend/control-center/src/pages/Connectors/Providers/Twilio/TwilioConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/Zendesk/ConnectNewZendesk.tsx, frontend/control-center/src/pages/Connectors/RestartPopUp/index.module.scss, lib/typescript/model/Components.ts
=> [#3664] Fixed connect button and fixed notification color

frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx, frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx, frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx, frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/ChatPluginConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/ConnectorChatplugin.tsx, frontend/control-center/src/pages/Connectors/Providers/Dialogflow/ConnectorDialogflow.tsx, frontend/control-center/src/pages/Connectors/Providers/Dialogflow/DialogflowConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/Facebook/Messenger/ConnectorFacebook.tsx, frontend/control-center/src/pages/Connectors/Providers/Facebook/Messenger/FacebookConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/Google/ConnectorGoogle.tsx, frontend/control-center/src/pages/Connectors/Providers/Google/GoogleConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/Instagram/ConnectorInstagram.tsx, frontend/control-center/src/pages/Connectors/Providers/Rasa/ConnectorRasa.tsx, frontend/control-center/src/pages/Connectors/Providers/Rasa/RasaConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/Salesforce/ConnectNewSalesforce.tsx, frontend/control-center/src/pages/Connectors/Providers/Salesforce/SalesforceConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/Twilio/SMS/ConnectorTwilioSms.tsx, frontend/control-center/src/pages/Connectors/Providers/Twilio/TwilioConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/Twilio/WhatsApp/ConnectorTwilioWhatsapp.tsx, frontend/control-center/src/pages/Connectors/Providers/WhatsappBusinessCloud/ConnectorWhatsappBusinessCloud.tsx, frontend/control-center/src/pages/Connectors/Providers/WhatsappBusinessCloud/WhatsappBusinessCloudConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/Zendesk/ConnectNewZendesk.tsx, frontend/control-center/src/pages/Connectors/Providers/Zendesk/ZendeskConnect.tsx, frontend/control-center/src/pages/Inbox/ChannelsList/index.tsx, frontend/control-center/src/reducers/data/connector/index.ts, frontend/control-center/src/routes/routes.ts, frontend/control-center/src/services/getRouteForCard.ts, lib/typescript/model/Components.ts
closes #3662 (part I)
part II will be done in a follow-up PR :)
=> [#3662] Update DynamoDB with configuration values and remove enum ComponentName in model lib 

lib/typescript/components/alerts/SettingsModal/style.module.scss
=> [#3361] Fixed z-Index issue on customize page chatplugin

frontend/control-center/src/pages/Connectors/ChannelCard/index.tsx, frontend/control-center/src/pages/Connectors/ConfigStatusButton/index.module.scss, frontend/control-center/src/pages/Connectors/ConfigStatusButton/index.tsx, frontend/control-center/src/pages/Connectors/ConnectorWrapper/index.tsx, frontend/control-center/src/pages/Connectors/index.tsx, frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx, frontend/control-center/src/services/getComponentStatus.ts, lib/typescript/assets/scss/colors.scss
=> [#3668] Added not healthy to connectors

frontend/control-center/src/App.tsx, frontend/control-center/src/pages/Inbox/InboxOutlet.tsx, frontend/control-center/src/routes/routes.ts
=> [#3681] Control Center: reorganize routing for Inbox component

frontend/inbox/handles/index.ts, frontend/inbox/src/actions/contacts/index.ts, frontend/inbox/src/components/ContactDetails/index.tsx, frontend/inbox/src/components/DialogCustomizable/index.module.scss, frontend/inbox/src/components/Sidebar/index.module.scss, frontend/inbox/src/pages/Contacts/ContactInformation/index.module.scss, frontend/inbox/src/pages/Contacts/ContactInformation/index.tsx, frontend/inbox/src/pages/Contacts/ContactListItem/index.module.scss, frontend/inbox/src/pages/Contacts/index.module.scss, frontend/inbox/src/pages/Contacts/index.tsx, frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx, integration/ui/list_contacts_page.spec.ts
=> [#3469] Removed animation contacts and added installed check

frontend/control-center/src/pages/Catalog/index.tsx
=> [#3723] Sort catalog by installed, name, price

lib/typescript/render/SourceMessagePreview.tsx
=> [#3725] Rendering of WhatsApp Cloud messages in the Conversation List Preview 

docs/docs/concepts/release-process.md, docs/docs/getting-started/installation/aws.md, docs/docs/getting-started/installation/minikube.md
- Improve AWS and Minikube installation docs
- Clarify some of the release items
=> [#2754] Improve installation and release docs

frontend/control-center/src/pages/Connectors/index.tsx, frontend/control-center/src/pages/Inbox/ChannelsList/index.tsx, frontend/control-center/src/services/format.ts, frontend/inbox/handles/index.ts, integration/support/createChatPluginConversation.ts, integration/ui/connect_chatplugin.spec.ts, lib/typescript/translations/translations.ts
closes #3730
- cypress connector update
- & small fixes
=> [#3730] cypress connector update

backend/components/facebook/connector/BUILD, backend/components/facebook/connector/src/main/java/co/airy/core/sources/facebook/WebhookController.java, backend/components/facebook/connector/src/test/java/co/airy/core/sources/facebook/WebhookControllerTest.java, backend/components/whatsapp/connector/BUILD, backend/components/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/WebhookController.java, backend/components/whatsapp/connector/src/test/java/co/airy/core/sources/whatsapp/WebhookControllerTest.java, lib/java/crypto/src/main/java/co/airy/crypto/Signature.java
=> [#3616] Validate incoming facebook webhook signatures

frontend/control-center/public/start.html
=> fix routing

frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx, frontend/control-center/src/pages/Catalog/index.tsx, frontend/control-center/src/pages/Connectors/ChannelCard/index.tsx, frontend/control-center/src/pages/Connectors/ConfigStatusButton/index.tsx, frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx, frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx, frontend/control-center/src/pages/Connectors/EmptyStateConnectors/index.module.scss, frontend/control-center/src/pages/Connectors/InfoCard/index.tsx, frontend/control-center/src/pages/Connectors/index.tsx, frontend/control-center/src/pages/Status/index.tsx, frontend/control-center/src/selectors/connectors.ts, frontend/control-center/src/services/getComponentStatus.ts, frontend/control-center/src/services/getRouteForCard.ts, lib/typescript/model/Components.ts, lib/typescript/model/Connectors.ts
=> [#3648] Added getMergedConnectors as useSelector

frontend/inbox/src/components/TopBar/index.tsx
=> [#3796] fix link topbar

frontend/control-center/src/components/TopBar/index.tsx, frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx, frontend/control-center/src/pages/Catalog/CatalogSearchBar/CatalogSearchBar.tsx, frontend/control-center/src/pages/Catalog/CatalogSearchBar/FilterCatalogModal/FilterCatalogModal.tsx, frontend/control-center/src/pages/Catalog/index.module.scss, frontend/control-center/src/pages/Connectors/ChannelCard/index.tsx, frontend/control-center/src/pages/Connectors/ConfigureConnector/SetConfigInputs/SetConfigInputs.tsx, frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.module.scss, frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx, frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx, frontend/control-center/src/pages/Connectors/Providers/Airy/ChatPlugin/sections/ConnectNewChatPlugin.tsx, frontend/control-center/src/pages/Connectors/Providers/Facebook/Messenger/FacebookConnect.tsx, frontend/control-center/src/pages/Connectors/Providers/WhatsappBusinessCloud/WhatsappConnect.tsx, frontend/inbox/src/components/TopBar/index.tsx, frontend/inbox/src/pages/Contacts/ContactInformation/index.tsx, frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/index.tsx, lib/typescript/components/cta/SmartButton/index.tsx, lib/typescript/components/inputs/Input/index.tsx, lib/typescript/components/inputs/Input/style.module.scss, lib/typescript/components/tooltip/index.module.scss, lib/typescript/translations/translations.ts
=> [#3800] Minor fixes

frontend/control-center/src/pages/Connectors/ConfigureConnector/index.tsx, frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx, lib/typescript/translations/translations.ts
=> [#3822] Added Notification Configurations

frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx, frontend/control-center/src/pages/Connectors/ConfigureConnector/index.tsx, frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx, frontend/control-center/src/pages/Connectors/ConnectorWrapper/index.tsx, frontend/control-center/src/selectors/connectors.ts, frontend/control-center/src/services/format.ts
=> [#3839] Adapted connectors useSelector according components.get response

backend/components/unread-counter/src/main/java/co/airy/core/unread_counter/dto/UnreadCountState.java
=> [#3835] Fix unread counter crash

backend/components/cognigy/src/main/java/co/airy/core/cognigy_connector/MessageHandler.java, backend/components/cognigy/src/main/java/co/airy/core/cognigy_connector/models/MessageSend.java, backend/components/cognigy/src/main/java/co/airy/core/cognigy_connector/models/MessageSendResponse.java, lib/typescript/render/SourceMessagePreview.tsx, lib/typescript/render/providers/chatplugin/ChatPluginRender.tsx, lib/typescript/render/providers/chatplugin/chatPluginModel.ts, lib/typescript/render/providers/chatplugin/components/QuickReplies/index.module.scss, lib/typescript/render/providers/chatplugin/components/QuickReplies/index.tsx, lib/typescript/render/providers/meta/MetaRender.tsx
=> [#3825] support cognigy ai non text flow nodes

frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.module.scss, frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx, lib/typescript/components/wrapper/ContentWrapper/index.module.scss
closes #3719 
--> changes made to the Catalog details page in order to support the components' descriptions new formatting
=> [#3719] Updating all Source Connector

frontend/control-center/src/pages/Connectors/ConnectedChannelsList/ChannelsListItem/index.module.scss, frontend/control-center/src/pages/Connectors/ConnectedChannelsList/ChannelsListItem/index.tsx, frontend/control-center/src/pages/Connectors/ConnectorConfig/index.tsx, frontend/control-center/src/pages/Connectors/ConnectorWrapper/index.tsx, lib/typescript/components/tooltip/index.module.scss, lib/typescript/components/tooltip/index.tsx, lib/typescript/translations/translations.ts
=> [#3642] Added tooltips to channel connectors

frontend/control-center/src/components/TopBar/index.module.scss, frontend/control-center/src/pages/Catalog/CatalogSearchBar/CatalogSearchBar.module.scss, frontend/control-center/src/pages/Catalog/CatalogSearchBar/CatalogSearchBar.tsx, frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.module.scss, frontend/control-center/src/pages/Connectors/ConnectedChannelsList/index.tsx, frontend/inbox/src/components/TopBar/index.module.scss, frontend/inbox/src/pages/Contacts/ContactInformation/index.module.scss, frontend/inbox/src/pages/Inbox/ConversationListHeader/index.module.scss, frontend/inbox/src/pages/Inbox/ConversationListHeader/index.tsx, frontend/inbox/src/pages/Inbox/Messenger/ConversationMetadata/index.module.scss, lib/typescript/assets/scss/animations.scss, lib/typescript/components/inputs/SearchField/index.tsx
=> [#3862] Fixed icons and improved animations

backend/components/installer/src/main/java/co/airy/core/api/components/installer/CatalogHandler.java, backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstalledComponentsHandler.java, backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallerHandler.java, backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallerHandlerCacheManager.java, backend/components/installer/src/main/java/co/airy/core/api/components/installer/model/ComponentDetails.java, backend/components/installer/src/main/java/co/airy/core/api/components/installer/model/InstallationStatus.java, backend/components/installer/src/main/resources/application.properties, backend/components/installer/src/test/java/co/airy/core/api/components/installer/CatalogHandlerTest.java, backend/components/installer/src/test/java/co/airy/core/api/components/installer/InstallerHandlerTest.java
=> [#3883] Feature add pending status to components.list call

frontend/control-center/src/components/ChannelAvatar/index.tsx, frontend/control-center/src/pages/Connectors/ConfigureConnector/SetConfigInputs/SetConfigInputs.tsx, lib/typescript/model/Source.ts, lib/typescript/translations/translations.ts
=> [#3894] fixes for ibm watson assistant

frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx, frontend/control-center/src/pages/Status/index.tsx
=> [#3886] fixed status page error

backend/components/ibm-watson-assistant/helm/templates/deployment.yaml, frontend/control-center/src/pages/Connectors/ConfigureConnector/SetConfigInputs/SetConfigInputs.tsx, lib/typescript/translations/translations.ts
=> [#3909] rasa control center fix

backend/components/installer/BUILD, backend/components/installer/src/main/java/co/airy/core/api/components/installer/CatalogHandler.java, backend/components/installer/src/main/java/co/airy/core/api/components/installer/GitHandler.java, backend/components/installer/src/main/java/co/airy/core/api/components/installer/HelmJobHandler.java, backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallationStatusComponentsHandler.java, backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstalledComponentsHandler.java, backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallerHandler.java, backend/components/installer/src/main/java/co/airy/core/api/components/installer/InstallerHandlerCacheManager.java, backend/components/installer/src/main/java/co/airy/core/api/components/installer/Stores.java, backend/components/installer/src/main/java/co/airy/core/api/components/installer/model/ComponentStatus.java, backend/components/installer/src/main/resources/application.properties, backend/components/installer/src/test/java/co/airy/core/api/components/installer/CatalogHandlerTest.java, backend/components/installer/src/test/java/co/airy/core/api/components/installer/InstallationStatusComponentsHandlerTest.java, backend/components/installer/src/test/java/co/airy/core/api/components/installer/InstallerHandlerTest.java, backend/components/installer/src/test/resources/test.properties, backend/model/component/BUILD, backend/model/component/src/main/java/co/airy/model/component/Component.java, backend/model/component/src/main/java/co/airy/model/component/MetadataRepository.java, infrastructure/helm-chart/templates/provisioning/kafka-create-topics.yaml, lib/java/kafka/schema/src/main/java/co/airy/kafka/schema/ops/OpsApplicationComponents.java
=> [3901 & 3900] Feature/3901 create kafka topic for components events

frontend/control-center/src/components/Sidebar/index.tsx, frontend/control-center/src/pages/Connectors/index.tsx, frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx, frontend/control-center/src/services/getRouteForCard.ts, lib/typescript/model/Source.ts, lib/typescript/translations/translations.ts
=> [#3927] Added airy contacts to catalog

infrastructure/terraform/install/uninstall.sh, infrastructure/terraform/modules/gcp-gke/main.tf, infrastructure/terraform/modules/gcp-gke/outputs.tf
=> [#3923] Use auth-provider in GCP kubeconfig file

backend/components/unread-counter/src/main/java/co/airy/core/unread_counter/UnreadCounterController.java, infrastructure/helm-chart/templates/components/ingress.yaml
=> [#3941] add ingress rule for /conversations.mark-read

infrastructure/terraform/install/gcp-gke/outputs.tf
Fix of the gcp-gke terraform modules output file
=> [#3943] Fix of the gcp-gke terraform modules output file

docs/docs/api/endpoints/components.md
=> [#3949] Updated conversation.list docs

infrastructure/terraform/modules/gcp-gke/main.tf
=> [#3957] Disable Preemptible nodes in GCP

docs/docs/concepts/kafka.md
=> [#3960] Updated kafka topic link

frontend/control-center/src/pages/Status/ComponentListItem/ItemInfo.tsx
=> [#3969] Fixed health status icon

frontend/control-center/src/pages/Catalog/CatalogItemDetails/index.tsx, lib/typescript/model/Components.ts, lib/typescript/translations/translations.ts
closes #3841 
airyhq/catalog is already prepared for this.
=> [#3841] Add translations catalog components

README.md
Updated Readme to reflect Data Launch
=> Updated Readme to reflect Data Launch

docs/docs/guides/contributing-to-airy.md
=> [#3974] Fix pushing local images to Minikube

infrastructure/helm-chart/charts/ingress-controller/templates/letsencrypt.yaml, infrastructure/terraform/modules/core/main.tf
=> [#3988] Fix deprecated tf parameter

docs/docs/getting-started/installation/helm.md, infrastructure/helm-chart/templates/components/api-components-installer/deployment.yaml
=> [#3995] Add init container to the installer

frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx
=> [#3997] Fixed navigation chatplugin

CONTRIBUTING.md, README.md, infrastructure/helm-chart/templates/components/ingress.yaml
=> [#4011] Fix broken links in the docs

backend/components/whatsapp/connector/src/main/java/co/airy/core/sources/whatsapp/WebhookController.java, backend/components/whatsapp/connector/src/test/java/co/airy/core/sources/whatsapp/WebhookControllerTest.java, backend/components/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/EventsRouter.java, backend/components/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/model/Value.java, backend/components/whatsapp/events-router/src/main/java/co/airy/core/sources/whatsapp/model/WebhookEntry.java, lib/java/crypto/src/main/java/co/airy/crypto/Signature.java
=> [#4015] Fix new Whatsapp ingestion payload structure

lib/typescript/render/outbound/whatsapp.ts
=> [#4017] Whatsapp send message payload updated

frontend/control-center/src/pages/Catalog/CatalogCard/index.module.scss, frontend/control-center/src/pages/Catalog/CatalogCard/index.tsx, frontend/control-center/src/pages/Catalog/CatalogFilter/index.module.scss, frontend/control-center/src/pages/Catalog/CatalogFilter/index.tsx, frontend/control-center/src/pages/Catalog/index.tsx, frontend/control-center/src/pages/Connectors/index.tsx, lib/typescript/assets/scss/colors.scss, lib/typescript/components/general/FilterBar/FilterDropdown/index.module.scss, lib/typescript/components/general/FilterBar/FilterDropdown/index.tsx, lib/typescript/components/general/FilterBar/index.module.scss, lib/typescript/components/general/FilterBar/index.tsx, lib/typescript/model/Source.ts, lib/typescript/translations/translations.ts
=> [#4034] Add filter in catalog

infrastructure/helm-chart/templates/provisioning/job-kafka.yaml, infrastructure/helm-chart/values.yaml
=> [#4035] Customize number of partitions

backend/components/admin/BUILD, backend/components/admin/src/main/java/co/airy/core/admin/RegistryProxy.java, backend/components/admin/src/test/resources/test.properties, infrastructure/helm-chart/templates/components/api-admin/deployment.yaml, infrastructure/helm-chart/templates/components/ingress.yaml
=> [#4057] Expose kafka API in rest proxy

docs/docusaurus.config.js, docs/package.json, docs/src/components/ButtonBox/index.js, docs/src/components/Image/index.js, docs/src/components/SuccessBox/index.js, docs/src/components/SuccessBox/styles.module.css, docs/src/components/TLDR/index.js, docs/yarn.lock, yarn.lock
=> [#4068] Fix Docs build

README.md
**Fixes Issue #4086** 
This PR:
- Updates the link to contributing guide in the README.md file
=> [#4086] Fix link to contributing guide

backend/components/streams/BUILD, backend/components/streams/auth.go, backend/components/streams/cors.go, backend/components/streams/helm/BUILD, backend/components/streams/helm/Chart.yaml, backend/components/streams/helm/templates/configmap.yaml, backend/components/streams/helm/templates/deployment.yaml, backend/components/streams/helm/templates/service.yaml, backend/components/streams/helm/values.yaml, backend/components/streams/main.go, backend/components/streams/streams_create.go, backend/components/streams/streams_delete.go, backend/components/streams/streams_info.go, backend/components/streams/streams_list.go, docs/docs/api/endpoints/streams.md, docs/docs/getting-started/glossary.md, docs/sidebars.js, go.mod, go.sum, lib/go/httpclient/BUILD, lib/go/httpclient/httpclient.go, lib/go/httpclient/streams.go, lib/go/payloads/BUILD, lib/go/payloads/streams.go
=> [#4053] Streams backend
